### PR TITLE
CollisionFX update

### PR DESCRIPTION
**Pull request by Momo555**
upload of CollisionFX 4.0 to archive.org
Creation of ckan file - should display now as 1.2.2 compatible

### CODE REVIEW

**Comment by Olympic1** [comment]
Did you ask the author to add it back to CKAN?

If so, pointing to his [GitHub](https://github.com/pizzaoverhead/CollisionFX/releases) would be better

**Comment by linuxgurugamer** [comment]
I've asked Pizzaoverhead if it's ok to add this.
Beyond that, we should NOT go to archive.org for active mods.  If Pizza says it's ok, it should be updated to go to his Github instead: https://github.com/pizzaoverhead/CollisionFX

**Comment by Momo555** [comment]
My bad, tried to correct this.
Deleted the file from archive.org and changed the link to Pizzaoverhead's Github. Thanks for the feedback

**Comment by politas** [comment]
This should also be a .netkan file in the Netkan repo, so future updates are scraped (Assuming pizzaoverhead agrees to it being added)

**Comment by politas** [comment]
[CollisionFX license](https://github.com/pizzaoverhead/CollisionFX/blob/master/LICENSE) is GPL-2.0

**Comment by Momo555** [comment]
I do not have the history behind why this mod is no longer updated (I just joined).
I missed the netkan file. I can change it if Pizzaoverhead give us his permission to list this mod.

**Comment by linuxgurugamer** [comment]
I just pinged him in the thread, hopefully he will respond.
While you wait, why not remove this and do a proper .netkan file (as suggested earlier)

**Comment by linuxgurugamer** [comment]
Also, note that the current release has a .version file in, so you can rely on that and not have to specify the x_netkan_override which is in the old .frozen file

**Comment by Momo555** [comment]
OK. I deleted the ckan file and created the netkan file in [another request](https://github.com/KSP-CKAN/NetKAN/pull/5422)

**Pull request closed without merging**
