### PR TITLE
Correct license

### PR DESCRIPTION
**Pull request by plague006**
Closes https://github.com/KSP-CKAN/CKAN/issues/1749

### CODE REVIEW

**Comment by politas** [comment]
Given that the actual wording was "more like WTFPL", we should say "unrestricted" at least.

**Comment by plague006** [comment]
> License is CC BY except for the parachute model, ask CardBoardBoxProcessor if you want to use it for anything, he made it.

**Comment by plague006** [comment]
I recognize that we're extracting only `EVAParachutes.dll` for this module, but due to mirroring we don't really want to select a license that will have us mirror unknown or restricted content.

**Comment by politas** [comment]
Ah, I was forgetting that we're extracting the DLL from a complete VNG package. It's a bit of a headache.
Wish I had the skills to make a parachute model I could donate to make the whole thing CC-BY.

**Pull request merged**
