### PR TITLE
Astronomer's Pack: Core Packages

### PR DESCRIPTION
**Pull request by SpaceTeph**
Astronomer's Pack consists of many different parts, most of which I have managed to split up into mods that can be managed by CKAN. Those are:

* A core part with:
 * Base EVE configuration with volumetric clouds in low, medium and high resolution variants
 * PlanetShine configuration
 * Distant Object Enhancement configuration
* Optional features, all implemented as supplementary EVE configuration files and textures:
 * Atmospheric scattering
 * Sandstorms and surface dust
 * Snow
 * Surface glow
 * Auroras in low and high resolution variants
 * Clouds for Eve and Jool in low, medium and high resolution variants
 * Lightning

Extra features not included in CKAN for various reasons are:

    Lens Flare (replaces core game files in KSP_Data)
    Holiday Season City Lights (replace files already installed by the pack)
    New Sun (replaces files already installed by the pack)
    Skyboxes (not included in the pack's ZIP file)

I am submitting this to CKAN-meta because NetKAN cannot automatically check for updates on this one and the structure (as well as the complexity) of the pack's ZIP file makes it improbable that new releases can be automatically supported.

This PR contains the core packages that are needed by the options.

### CODE REVIEW

**Comment by SpaceTeph** [comment]
Let's do this again.

**Comment by SpaceTeph** [comment]
...argh. Sorry, I'm not too good with that whole github workflow thingie.

**Comment by SpaceTeph** [comment]
@hakan42 this PR will hopefully be of interest :grinning: 
I have put up a repository for further testing that is a copy of the PR's contents [there]
(https://github.com/SpaceTeph/CKAN-meta-testing). You can use it in CKAN. It seems the, erh, metapackage has issues with the suggested mods, but it otherwise installs well.

The hard part is getting the installed mod to load in a 32-bit version of KSP, though. It works, but nearly without any other mods.

**Comment by hakan42** [comment]
Oh wow, I guess I will have to set up a third KSP instance, this one nearly empty :smile:

Good thing that using CKAN makes KSP management is so easy :smile_imp:

**Comment by SpaceTeph** [comment]
Have fun. It was a lot of work and there was a good amount of errors to fix here and there due to the large amount of packages involved, but my hope is that it was worth the effort.

**Comment by hakan42** [comment]
Crossing fingers and merging :smiling_imp:

**Pull request merged**
