### PR TITLE
KAS added ksp min and max vice single fixed version

### PR DESCRIPTION
**Pull request by Murdabenne**

### CODE REVIEW

**Comment by Murdabenne** [comment]
FYI build fails due to KIS being 1.0.2.  KIS is convewrted to min/max in PR#649, so this is a spurious error - committing it first will fix this

**Comment by SkyMarshal** [comment]
#rebuild

**Comment by SkyMarshal** [comment]
Oh, derp.  Didn't see this was KAS and the other was KIS.

**Comment by pjf** [comment]
Jenkins loves this and so do I.

**Pull request merged**
