### PR TITLE
Add new TimeControl releases

### PR DESCRIPTION
**Pull request by politas**
It looks like the Netkan bot is failing without reporting the failures to the status page.

### CODE REVIEW

**Comment by HebaruSan** [comment]
There are commits to master in this folder that may or may not conflict; can you please rebase?

**Comment by ntwest** [comment]
Please note that I had a couple releases that I had to pull due to issues, perhaps that's what happened? There are now 2 releases, one for 1.3, and one for 1.3.1.

1.3: https://github.com/ntwest/TimeControl/releases/tag/2.7
1.3.1: https://github.com/ntwest/TimeControl/releases/tag/2.8.1

**Comment by HebaruSan** [comment]
Yeah, this change is addressing part of that (adding 2.7, which got skipped), but I think 2.8.x also needs to be removed from the index. And 2.8.1 got added by the bot in the meantime, so I want to make sure both versions are consistent.

**Comment by HebaruSan** [comment]
OK, I rebased this locally, and the files for 2.8.1 are identical, so this is only adding 2.7, which is good. Merging...

**Pull request merged**
