### PR TITLE
Patch ModernChineseFlagPack - Please advise

### PR DESCRIPTION
**Pull request by Dazpoet**
This patch does not work!

Now with that out of the way, why doesn't it work? I've tried dl'ing the file from the adress and it works just fine. I looked at other mods that download from curse (KAS and KIS) and they work fine so it is beyond me why this doesn't work...

Currently the mod returns a 404 in CKAN due to having been removed from KS. This patch won't make the situation worse but alas it doesn't seem to fix the problem either. Some help would be deeply appreciated :)

Relevant: https://github.com/KSP-CKAN/NetKAN/pull/842

### CODE REVIEW

**Comment by hakan42** [comment]
You seem to have an extra comma at line 17:

ValueError: Expecting property name: line 17 column 3 (char 372)
Build step 'Execute shell' marked build as failure

**Comment by Dazpoet** [comment]
So I removed the extra comma but when attempting to install I still get this error
```
O:\Kerbal Space Program>ckan install -c ModernChineseFlagPack-1.4.ckan
About to install...

 * ModernChineseFlagPack 1.4

Continue? [Y/N] y

Downloading "http://www.curse.com/shareables/kerbal/225651-modern-chinese-flag-p
ack/download"
0 kbps - downloading - 0 MiB left - 100%
Installing mod "ModernChineseFlagPack 1.4"
Unhandled Exception: CKAN.FileNotFoundKraken: Trying to install ModernChineseFlagPack 1.4, but it's not downloaded
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, NetAsyncDownloader downloader)
   at CKAN.CmdLine.Install.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.Main(String[] args)

O:\Kerbal Space Program>
```
I tried emptying my cache to see if that was the problem but no dice. I still fail to see why it won't download.

**Comment by Dazpoet** [comment]
Seems Jenkins have the same problem since he reports
```
CKAN.FileNotFoundKraken: Trying to install ModernChineseFlagPack 1.4, but it's not downloaded
```

**Comment by pjf** [comment]
Aha! Looks like this download should be [this](http://addons-origin.cursecdn.com/files/2222/856/Bydysawd.zip), which is machine friendly, rather than the current URL which requires a browser, and javascript (as curse then bounce you from that page to the actual download itself).

**Comment by pjf** [comment]
Merged with adjustments. :) Many thanks!

**Comment by Dazpoet** [comment]
How did you find that link? I've been looking all over trying to find a direct link but apperantly my google-fu is not as strong as I'd like it to be

**Comment by pjf** [comment]
In this case I checked activity using the RequestPolicy plugin for Firefox, but the net panel on Firebug would have likely worked just as well. (Or whatever web-dev-friendly plug-ins exist for your browser.)

**Pull request merged**
