### PR TITLE
Initial addition of TestFlight to CKAN

### PR DESCRIPTION
**Pull request by jwvanderbeck**

### CODE REVIEW

**Comment by hakan42** [comment]
Could you please convert the file with proper line ending characters? The pull request shows everything a one huge line which makes reviewing pretty hard :smile:

**Comment by jwvanderbeck** [comment]
Is this a requirement? I am auto generating the file during my build process.

**Comment by jwvanderbeck** [comment]
Going to close this and re-release a new version after I modify my code to pretty print the JSON

**Comment by hakan42** [comment]
Not so much a requirement but rather a nice-to-have. The netkan generator creates pretty printed json too :smile:

**Comment by hakan42** [comment]
@jwvanderbeck , by the way, if you have your releases on github, you don't need to write up a ckan file for each release you make.

Let's just write a netkan file, and leave it to netkan-bot to discover your releases, that way, you would benefit from our automation and any fixes / enhancements we make along the way :smiling_imp:

**Comment by jwvanderbeck** [comment]
@hakan42 unfortunately due to my process of releasing both a Stock and Realism Overhaul version for every release, I can't find a way to do it with netkan files.  I can't point you to GitHub releases because your system wouldn't know which it pick up unless i've missed something.

I use Github tags to drive my automated builds, so I always have tags like "0.4.6.1-Stock" for one release and "0.4.6.1-RealismOverhaul" for the other.

Unless i've missed something in your system, after reading the docs I came to the conclusion that I would have to generate .ckan files myself for every release.  That isn't a huge problem since I can autogenerate them through my build process.  The only real annoyance is having to create the PR by hand.

**Comment by hakan42** [comment]
Actually.... Please go ahead and do what is best for your workflow. Having the pretty-printed json will allow easier reviewing though. When I amended netkan to do the pretty printing, I chose indenting by four space characters and letting the Newtonsoft generator do the rest of the heavy lifting.

If I get around to it, I might experiment a bit, maybe netkan can already support your use case. It would save you the creating of the PR, and us the "accepting" part. In case you did not notice, I love automating stuff even if it saves only a few clicks every month or so :smiling_imp:

**Comment by jwvanderbeck** [comment]
Actually I already have it pretty printing now so will be doing a new release today.

As for automation, I assume your current way of working through Github with Netkan is you search the releases for the latest one?  Maybe if you added the ability to specify a string to filter on, that would work.

Here is my releases page: https://github.com/jwvanderbeck/TestFlight/releases
If you note there are two releases for 0.4.6.1 so if you just grabbed the latest one you wouldn't get them both. On CKAN I am essentially treating TestFlight as two separate mods.  One TestFlight-Stock and the other TestFlight-RealismOverhaul.  If I could make the Netkan point to my releases page AND specify a filter string to be checked against the TAG then I could set up two netkans one with a filter of "RealismOverhaul" and one with a filter of "Stock" and then when it queried my release page for the latest release that has a tag containing that string, it would match.

**Comment by hakan42** [comment]
Yep, you understood the inner workings of netkan pretty well.

We have *some* filtering, but it is against the zip files inside one released version. If you could take your comment above and write it as an issue against the CKAN-support project (or even CKAN-netkan, your choice), we could keep this discussion where someone could pick it up and support use cases like yours.

**Pull request closed without merging**
