### PR TITLE
Fixed links and added LICENSE.md

### PR DESCRIPTION
**Pull request by plague006**
Alternatively, the links can both go to outside sources (http://opensource.org/licenses/MIT and https://creativecommons.org/publicdomain/zero/1.0/legalcode) to future-proof them from any changes in the repo files/structure.

### CODE REVIEW

**Comment by Dazpoet** [comment]
This is the tiniest of OCD things but the order of ".ckan and .netkan files" is reversed when compared to https://github.com/KSP-CKAN/NetKAN/pull/1549

Could we have them in the same order for my sanities sake?

**Comment by plague006** [comment]
I actually swapped the order based on the repo. But I can respect someone else's OCD. :)

**Comment by pjf** [comment]
Linking to our MIT license file is the correct thing to do here, as it includes who holds the copyright (the "CKAN authors", which includes a link to all of them). It also avoids confusion where the MIT license [may be ambiguous](http://en.wikipedia.org/wiki/MIT_License#Various_versions). :)

**Comment by pjf** [comment]
Merged with thanks (although I made some slight adjustments to make sure the license displays properly when rendered as markdown).

**Pull request merged**
