### PR TITLE
RoverDude mods KSP1.05 cleanout

### PR DESCRIPTION
**Pull request by politas**
Removes all KSP 1.0.5 compatible versions of RoverDude's mods, adjusts metadata to limit some older versions to 1.0.4 where applicable, and removes all epochs that might cause problems going forward. Cleans everything out in preparation for author-hosted metadata.

### CODE REVIEW

**Comment by politas** [comment]
Took a bit of git/github research to figure out how to do this. I have backups of all the deleted netkans (though I assume rollbacks are possible in any case, I just haven't had cause to work them out, yet.)

**Comment by politas** [comment]
@pjf , can you look over this and KSP-CKAN/NetKAN#3018 and merge them, so we can have lovely fresh and presumably fixed RoverDude metadata?

**Comment by plague006** [comment]
This is too much for me to review this weekend, but I'll note that we don't want to remove existing metadata. The author won't be hosting metadata, they'll be hosting netkans which will generate metadata here in ckan-meta. With that said, consistent versioning remains important to ensure existing installations of mods are able to be upgraded. If we remove epochs that previous existed, any user with a version installed that contains an epoch will not have any new (non-epoched) versions available as updates.

**Comment by politas** [comment]
In the self-hosted Netkans, Roverdude is (so far) maintaining the epochs. He was quite insistent that we should clear out all the old metadata, as the current situation has poor installation instructions and it's all broken.This change clears out all the 1.0.5 relevant metadata as a compromise. I've also removed the need for the lazy epochs that seem to have been set merely to avoid updating old CKANs to reduce promiscuity. These mods should never have had epochs set.

I started a pull request on RoverDude's netkan repo to remove the epochs, remembered that this woudl cause users to not get updates, and closed the PR unmerged with a comment explaining the issue, so hopefully RoverDude will get the message about the epochs.

**Comment by CovertJaguar** [comment]
Is this still relevant or should it be closed?

**Comment by politas** [comment]
RoverDude was insisting this be done so that he could self-publish. I don't think it was ever necessary.

**Comment by plague006** [comment]
> I don't think it was ever necessary.

:+1:

**Pull request closed without merging**
