### PR TITLE
Create MissionController2-1.34.ckan

### PR DESCRIPTION
**Pull request by malkuth1974**

### CODE REVIEW

**Comment by plague006** [comment]
Opening curly brace `{` is missing.

**Comment by plague006** [comment]
From looking at the release list of your repo we haven't used netkan in the past because all your releases have been tagged as pre-release. If you're planning on tagging as full releases from here on out, we can use a .netkan file to automatically scrape for new versions to index. ksp version compatibility would be scraped from the .version file, no work would ever need to be performed to keep your mod up to date unless the install instructions changed.

**Comment by malkuth1974** [comment]
Since I no longer have Kerbal Stuff to host mods I will be releasing on GitHub from now on.  Sorry about the curry bracket.

**Comment by plague006** [comment]
Pushing this to give our users earlier access to your mod with the caveat that once https://github.com/KSP-CKAN/NetKAN/pull/3690 is merged, some of this metadata will be overwritten by @netkan-bot. See https://github.com/KSP-CKAN/NetKAN/pull/3690 for more info.

**Pull request merged**
