### PR TITLE
KRnD fix Name

### PR DESCRIPTION
**Pull request by politas**
Ampersands are not handled well by the client

### CODE REVIEW

**Comment by politas** [comment]
A changed metanetkan target doesn't appear to trigger a a new .ckan build

**Comment by techman83** [comment]
Won't be triggered, but will be picked up by the indexer on its regular run. LGTM.

**Comment by politas** [comment]
That might make sense if the indexer only ran weekly.

**Comment by techman83** [comment]
@politas hmm, I'm really not sure (sorry busy week), the indexer is simple in design. 

Did netkan generate changes? Yes/no
  - No, do nothing.
Do they pass validation? Yes/No
  - No, log error in status.
Yes to both -> Commit

I'll need to have a closer look.

**Comment by politas** [comment]
I can only guess that there's a point where some tests for changes are failing and dropping out completely rather than continuing to check the rest of the file.

**Pull request merged**
