### PR TITLE
Update MiniSampleReturnCapsule-v1.3.ckan 🚀 👁️‍🗨️ 

### PR DESCRIPTION
**Pull request by zer0Kerbal**
SpaceDock updated - however depends/suggests/recommends/tags, _etc._ updated in readme.md
🐰 
Please and thank you!

any way can remove the v in previous version listings?

### CODE REVIEW

**Comment by HebaruSan** [comment]
Don't do PRs in CKAN-meta, this is machine-generated data. I'll start the right changes in the proper place.

**Comment by HebaruSan** [comment]
Oops, committed to master when I meant to start a PR. I guess we can see how it goes.

https://github.com/KSP-CKAN/NetKAN/commit/c2155c7ec9ca187623e8f7dec699c78aab6f1c78

**Comment by HebaruSan** [comment]
@zer0Kerbal, the homepage field is pulled from SpaceDock, you can edit it there.

**Comment by HebaruSan** [comment]
FYI, your `Localization/readme.md` links to HebaruSan/PlanningNode in two places. :grinning:

**Comment by zer0Kerbal** [comment]
I always mess that up. fixing it (hopefully) permanently now. 😭

**Pull request closed without merging**
