### PR TITLE
EditorExtensions 2.2 is not that forwards compatible, either.

### PR DESCRIPTION
**Pull request by SkyMarshal**

### CODE REVIEW

**Comment by SkyMarshal** [comment]
#rebuild

**Comment by SkyMarshal** [comment]
@pfj @dbent It looks like the merge build is failing as it removes a 1.0.4 compatible version... which shouldn't be.

**Comment by dbent** [comment]
That's fine, it's a limitation of the build environment that only targets one version of KSP.

**Comment by SkyMarshal** [comment]
Thank you.

**Pull request merged**
