### PR TITLE
Add TestFlight 0.4.6.2

### PR DESCRIPTION
**Pull request by jwvanderbeck**

### CODE REVIEW

**Comment by Ippo343** [comment]
Hey @jwvanderbeck ! Thanks for contributing.
Shouldn't the RO version depend on RealismOverhaul too? Right now it can be installed in stock too..

**Comment by jwvanderbeck** [comment]
Splitting it into three packages is not going to happen because then anyone doing a manual install would have to download two packages.

You are correct though I should have put dependencies on RO.  I mean its a soft dependency only in that it just makes no sense to install it otherwise, but I should probably make it explicit.  I'll do that for the NEXT version though ok?

**Comment by Ippo343** [comment]
Actually no, there's no need to have two separate zips. We can make two packages that both download the same zip file and only take what they need.

If you want you can skip the dependency on RealismOverhaul (you are the author, it's your call), but I strongly advise you to do it early.

I am busy right now, I'll make the config packages as soon as I get the chance, ok?

**Comment by jwvanderbeck** [comment]
Truth is I'm probably going to stop making the Stock version soon anyway.

**Pull request closed without merging**
