### PR TITLE
Remove 1.99.99 from old SETI versions

### PR DESCRIPTION
**Pull request by HebaruSan**
This is part of #1590 with just the SETI mods included.
1.99.99 game versions are replaced with the actual game versions as well as can be determined.

### CODE REVIEW

**Comment by HebaruSan** [comment]
For future reference, a command to pre-validate commits to save on Jenkins credits:

```bash
for X in $(git show --name-only --pretty=''|grep -v frozen) ; do  netkan.exe --validate-ckan $X ; done
```

**Comment by HebaruSan** [comment]
The graph in #1590 shows about 3 hours of activity before running out of credits. If this pass doesn't work, we'll take a break.

**Comment by HebaruSan** [comment]
I think the validation succeeded, but it then failed while attempting to **report** success...

> Set GitHub commit status (universal)] SUCCESS on repos 
> Setting commit status on GitHub for https://github.com/KSP-CKAN/CKAN-meta/commit/645f2f4144c235b1cc4cdce02e0eca5250d50537
> ERROR: Build step failed with exception
> java.net.SocketTimeoutException: Read timed out: No data received within 15000ms.  Perhaps the docker API (tcp://127.0.0.1:4243) is not responding normally, or perhaps you need to increase the readTimeout value.

Should be safe to merge.

**Comment by techman83** [comment]
Most likely. Long running job + no cpu credits = a very sluggish java vm.

**Pull request merged**
