### PR TITLE
Updating ENB with latest version

### PR DESCRIPTION
**Pull request by kitoban**
ENB is showing out of date information.
https://kerbalstuff.com/mod/411/Enhanced%20Navball is an out of date version.

### CODE REVIEW

**Comment by AlexanderDzhoganov** [comment]
Can't really fix this from our site, bug the mod developer to update on KS.

**Comment by kitoban** [comment]
I can't at the moment, I am the mod developer but a 3rd party has uploaded
to KS, which I am trying to sort on there as well.

**Comment by hakan42** [comment]
There is one comma too many after the x_curse line. Please fix that and repush

**Comment by kitoban** [comment]
I've fixed the comma in the next fix, but I have got control on KS and this is now up to date on the latest version, would you prefer a push or wait on KS?

**Comment by hakan42** [comment]
In that case, maybe just close this PR and wait to KS. Automated stuff helps everyone :smiling_imp:

**Pull request closed without merging**
