### PR TITLE
Bring flag-only mods to the same version, and add a comment to identify them.

### PR DESCRIPTION
**Pull request by plague006**
One more step toward #623's completion.

### CODE REVIEW

**Comment by techman83** [comment]
Any flag hosted on KS likely isn't there anymore as it's against their mod policy.

**Comment by techman83** [comment]
We should probably remove these. I'll leave this open so it can be attended to.

**Comment by plague006** [comment]
@techman83 Why would we remove them? There are only 2: 1 hosted on curse and 1 on KS as part of `AlternateResourcePanel`

**Comment by techman83** [comment]
@plague006 I mean remove the KS ones that are failing. (I thought they were all KS ones, sorry may not have looked hard enough).

KS Has the following policy:
> Kerbal Stuff is a website for hosting mods. We have a couple of basic rules about what you can upload here
> - If you didn't write code (or parts), it probably doesn't belong here. No crafts. No flag packs. And so on.
> - Only upload mods you have the right to distribute. Check licensing!

> That's it! If you upload something that doesn't adhere to these rules, we will remove it. Otherwise, you're good to go!

So I'd suggest that's why the Flags are failing to download.

**Comment by plague006** [comment]
You're right that's my mistake, I only tried downloading the most recent versions of each.
`ModernChineseFlagPack-1.2` and `ModernChineseFlagPack-1.3`are dead links.

**Comment by plague006** [comment]
Can .ckans be deleted without causing issues to end users? I thought that was a big taboo?

**Comment by techman83** [comment]
Yeah they can be (if not we have bugs to squash). Removing ckan files  is not taboo as such, More there needs to be a good reason to do so.

The metadata for those ckans was likely only valid for a brief amount of time on KS so we need to either fix them by pointing them at their current location if it exists in an indexable manner or remove them.

If we use a PR that refers this issue we can always revert it if it turns not to be the best way to handle this.

**Comment by Gustavo6046** [comment]
What about adding Agar.io skins into KSP flags? Just a idea.
For more on Agario and its skins, check www.agarioguide.com and www.agarioguide.com/skins respectively. I say, maybe to parody the game. Also many skins are country flags, though my Brazil (homecountry) flag made specially for KSP is overall much better.

**Comment by plague006** [comment]
This issue isn't about adding flags, it's about modifying the flags already present.

**Comment by Gustavo6046** [comment]
Ops... Whatever I done an nice Brazil flag. Where do I post

**Comment by plague006** [comment]
Crossing fingers that removing the old versions of ModernChineseFlagPack doesn't cause issues for people. Passes local. Merging.

**Pull request merged**
