### PR TITLE
updated PreciseNode

### PR DESCRIPTION
**Pull request by TeddyDD**

### CODE REVIEW

**Comment by TeddyDD** [comment]
I don't know why this failed, works for me.

**Comment by Dazpoet** [comment]
Jenkins is using a strictly enforced KSP version of 1.0.0 so he fails this since he cannot use the supplied .ckan file nor can he find a version that works for 1.0.0.

Is this precisenode version strictly locked to 1.0.2 or would it also work with 1.0.x? If the latter is the case maybe consider changing the ksp_version to 1.0 as outlined [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-12-30-Apr-2015?p=1893886&viewfull=1#post1893886)

**Comment by TeddyDD** [comment]
It's hard to tell according to change log
```
1.1.3, 2015-05-02
- Fixed NullReferenceException in map mode.
- Updated for KSP 1.0.2.

1.1.2, 2014-12-16
- Updated for KSP 0.90.0.
(...)
```
I'll change ksp_version to 1.0
Anyway I think Jenkins behaviour should be tweaked :)

**Comment by Dazpoet** [comment]
I'm considering switching Jenkins to a 1.0 install but I'm not sure that's better or worse than 1.0.2

**Comment by TeddyDD** [comment]
Dunno, Jenkins side of ckan is magic for me :)

**Comment by Dazpoet** [comment]
Me to but you do pick things up here and there so I'm trying to learn as to not be handicapped when stuff like this happens :p

**Comment by TeddyDD** [comment]
Meh, the same problem with Kerbal Alarm Clock :C I'll open an issue

**Pull request merged**
