### PR TITLE
Convert all FOSS mods from KS to download from i.52k.de

### PR DESCRIPTION
**Pull request by pjf**
Thanks to @V1TA5, we have a mirror of the freely redistributable mods
from KS. This change re-writes extant CKAN metadata files that have
free licenses to use the i.52k.de server.

Created by running 1f3e252e9ae3dbad6e123d72dd1a255e32484a6e of
kspstuff-migrate.pl in https://github.com/pjf/KS-KSPStuff-Migration

### CODE REVIEW

**Comment by websterhamster** [comment]
For the lay user (like me), how do I use this?

**Comment by Olympic1** [comment]
@websterhamster when this get's merged, re-open your CKAN and then download the mods like you always did.

**Comment by websterhamster** [comment]
Aha, thanks! ;)

**Comment by pjf** [comment]
Things to note:

- This is about 80% of all available mods I *could* convert. The remaining 20% have non-free licenses, and I'm not touching those.
- Some of these mods are historical versions of mods that are in our indexer. The newer mods aren't changed, only their old-versions.
- We should consider i.52k.de to be temporary, so these changes are good for about a month.

**Pull request merged**
