### PR TITLE
Add muffler

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by techman83** [comment]
Hey @plague006 could you rebase to pickup the new build script.

**Comment by techman83** [comment]
Hmm maybe I need to fix it trying to test itself!

**Comment by plague006** [comment]
I don't... I don't think that went the way it should...

**Comment by plague006** [comment]
I have no idea if I did that right, and the green tick kinda surprised me.

**Comment by pjf** [comment]
It passes testing, so jenkins is picking up the right file, but it looks like everything else has been rebased on top of your commit, rather than your commit being rebased on top of everything else. :)

@plague006 : Do you mind if I adjust the mod identifier to `Muffler`(with an upper-case 'M') and then use my git-fu to merge bdaca91 without the extra commits?

**Comment by plague006** [comment]
By all means.

**Comment by pjf** [comment]
Merged with magic and thanks. :)

**Comment by plague006** [comment]
http://i.imgur.com/YsbKHg1.gif

**Comment by pjf** [comment]
@plague006 : Markdown lets you make this even better. :D 

    Magic...

Magic...

**Pull request closed without merging**
