### PR TITLE
PhoenixIndustriesCargoResupplySystem

### PR DESCRIPTION
**Pull request by plague006**
Resolves KSP-CKAN/NetKAN#1381

### CODE REVIEW

**Comment by Dazpoet** [comment]
conflict should be the same as provides to avoid wonky errors in the future.

Forumthread recommends MechJeb and KIS, maybe these files should do the same?

**Comment by plague006** [comment]
Adding recommends, not sure what you mean about conflicts and provides should be the same, used https://github.com/KSP-CKAN/CKAN-meta/blob/master/BananaForScale-large/BananaForScale-large-1.0.ckan as template.

**Comment by Dazpoet** [comment]
Ugh that one should also be changed then. Set the conflicts to be with `PhoenixIndustriesCargoResupplySystem` rather than the other mod. This is mostly used for mods who have different configs but makes for a nice standard.

Say we mysteriously get another mod which provides `PhoenixIndustriesCargoResupplySystem` the conflicts for both that and these two would need to be upgraded rather than just sticking a conflict with the provided identifier which originates from all of them.

**Comment by Dazpoet** [comment]
fails for obvious reasons. Since netkan.exe checked the files as ok and Jenkins validates them I'll merge this.

**Comment by Dazpoet** [comment]
I must admit I never forsaw this coming but damn! The reference to netkan above acctually includes exactly what we guarded against, namely a mod with the identifier we conflicted with :+1:

**Comment by plague006** [comment]
@Dazpoet the prophet. =)

**Pull request merged**
