### PR TITLE
[x] Science! V4.7 Go Live

### PR DESCRIPTION
**Pull request by thewebbooth**
[x] Science! V4.7 Go Live

Thank you!

### CODE REVIEW

**Comment by plague006** [comment]
Should it have a `ksp_version_max` or a flat `ksp_version` in case it breaks with whatever major ksp updates come down the line?

**Comment by thewebbooth** [comment]
I just copied someone else's ckan file!

OK, I'll change it and send you another pull.

**Comment by plague006** [comment]
No need to redo the pull, it looks fine.

**Comment by dbent** [comment]
Tested manually, merging. Thanks.

**Pull request merged**
