### PR TITLE
Update SimpleConstruction-1-4.0.2.6.ckan

### PR DESCRIPTION
**Pull request by zer0Kerbal**
Update SimpleConstruction-1-4.0.2.6.ckan
Was processing a cry for help on the forums when I saw the 'Updated' tag. Still the same mod so don't need that. :D adopted with full permission and blessing of original mod author.
📦 〽️ 

also - thought I would update the listings - haven't a clue what 'DeadskinsMeshSwitch' is still doing there. :D

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
one ❓ 
- why is the version number 1.4.0.2.6 when the actual version of SC! is 4.0.2.6?

**Comment by HebaruSan** [comment]
Changes here (CKAN-meta) won't take because they're continuously refreshed by the bot,

Try NetKAN instead:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SimpleConstruction.netkan

**Comment by HebaruSan** [comment]
> one 
> 
> * why is the version number 1.4.0.2.6 when the actual version of SC! is 4.0.2.6?

The version number isn't 1.4.0.2.6, it's 1:4.0.2.6. The part before the colon is called an "epoch":

- https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#epoch

**Comment by HebaruSan** [comment]
Changes as per the bot: a10f2454afce2d55aca09bc69e34009287be1523

**Comment by zer0Kerbal** [comment]
thanks! learn something every day! 🏫 👨‍🏫

**Pull request closed without merging**
