### PR TITLE
PartWizard 1.2.1 Added min-max KSP override for 1.0.4

### PR DESCRIPTION
**Pull request by Murdabenne**
Changed static ksp_version to ksp_version_min and _max.

### CODE REVIEW

**Comment by pjf** [comment]
Tagging in @hakan42 here (mentioned in the metadata content).

**Comment by Murdabenne** [comment]
I figured this was a minor delta. I was unsure how to notify - thanks for demonstrating that for me.

**Comment by pjf** [comment]
@Murdabenne : Aye, github makes mentions pretty easy. :)

On that note: @ozraven, we're marking your current release of PartWizard as working okay for using using 1.0.4 as well as 1.0.3. If this is in error, then please do let us know!

Many thanks,

~ pjf

**Comment by ozraven** [comment]
@pjf Yep, all good, thanks much.

**Pull request merged**
