### PR TITLE
Revert "Removed the core packages, they are in another branch"

### LINKED ISSUE #279: Astronomer's Pack packages unavailable
Thanks for packaging Astronomer's Pack but it appears that none of the packages are available to be installed through CKAN. From a quick look it seems to be because they depend on `AstronomersPack-Clouds`, `AstrnomersPack-PlanetShine`, or `AstronomersPack-DistantObjectEnhancement` which no longer appear in the repository.

Looks like they were removed in f7371848 by @SpaceTeph, which was part of #252, it's hard to tell from the PR diff because some of the new files are so similar to the deleted files that they appear as a file move rather than a deletion and add.

### PR DESCRIPTION
**Pull request by SpaceTeph**
This reverts commit f7371848d4a39e399a00de4b7f417cb573260a14.

Fixes #279.

### CODE REVIEW

**Comment by SpaceTeph** [comment]
Ah, the file had that syntax error...

**Comment by SpaceTeph** [comment]
@hakan42 if you would be so kind, please...

**Comment by hakan42** [comment]
Sure, when I am at my computer in another hour or so. Failing prs cannot be merged from the mobile...

**Comment by SpaceTeph** [comment]
@hakan42 : it's alright! Nobody here expects a five-minute reaction. I just pinged you to get your attention on the matter. :)

**Comment by hakan42** [comment]
#rebuild

**Comment by hakan42** [comment]
#rebuild

**Pull request merged**
