### PR TITLE
Stop testing build

### PR DESCRIPTION
**Pull request by techman83**
This will stop build.sh changes always failing.

I think @mgsdk's work on the NetKAN build script would apply to the CKAN-Meta. So I might take a look into porting it.

### CODE REVIEW

**Comment by pjf** [comment]
This looks great to me. Does jenkins keep KSP install state between runs, hence the need to "forget" them?

**Comment by techman83** [comment]
@pjf possibly it did previously, I was getting annoyed during testing locally - can remove it if required.

Every build now gets a fresh docker container which is terminated and removed post build.

**Comment by pjf** [comment]
@techman83 : Having thing which make sense for local testing is awesome. Thank you! :)

**Comment by pjf** [comment]
Merging with great thanks and the knowledge that if this screws things up, jenkins will tell us. :)

**Pull request merged**
