### PR TITLE
[WIP] Add SKY 1.5

### PR DESCRIPTION
**Pull request by pacbard**
Adds [SKY - Scale-up Kerbalism for You](http://forum.kerbalspaceprogram.com/threads/109753-1-0-2-SKY-Scale-up-Kerbalism-for-You-Includes-a-2nd-Gas-Giant-v1-5) ckan file. The download is on dropbox so we can't wrapt this up in a netkan. Both dependencies are indexed by CKAN already.

The mod description is rather scant, so let me know if you want to change it to something more poetic.

### CODE REVIEW

**Comment by dbent** [comment]
Can you add one or more [`author`](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#author) property? Otherwise it looks good.

**Comment by dbent** [comment]
Note to myself for #588: this presumably conflicts with 64K.

**Comment by pacbard** [comment]
Because I am at it, do you want me to add a conflicts stanza as well? There is a conflicts stanza, right?

**Comment by dbent** [comment]
Yeah, if you know of any mods in CKAN it conflicts with.

**Comment by pacbard** [comment]
I don't know if it conflicts. I'll leave as it is for right now.

**Comment by dbent** [comment]
#rebuild

**Comment by pacbard** [comment]
@dbent: Hold a minute to merge the pull request. There is a problem with the KSC switch config files. SKY replaces KSC switch files with its own. This requires some work to fix (probably split KSC switcher up in core an config).

**Comment by dbent** [comment]
OK, it looks like KSC Switcher [uses `GameDatabase` properly](https://github.com/jbengtson/KSCSwitcher/search?utf8=%E2%9C%93&q=GameDatabase) to get its configuration. So the proper thing would be for SKY to include a ModuleManager patch to edit it, rather than overwriting it. We shouldn't split mods up unless we absolutely have to.

**Comment by pacbard** [comment]
I'll close the pull request while I wait for the author to update the package. I'll update its status when I have more information about it.

**Pull request closed without merging**
