### PR TITLE
Added the optional features and meta-package for Astronomer's Pack.

### PR DESCRIPTION
**Pull request by SpaceTeph**
Astronomer's Pack. Optional features and a meta-package that does not do much more than depend on the core features and recommend/suggest the rest. Requires #250 to work.

### CODE REVIEW

**Comment by hakan42** [comment]
Now that I have merged #250, could you please re-visit this PR to clean up the reported conflicts?

**Comment by SpaceTeph** [comment]
*cracks knuckles* let's do this.

**Comment by SpaceTeph** [comment]
Argh, the rename detection in git thinks that the AstronomersPack-Auroras-4K package is a renamed and modified version of one of the AstronomersPack-Clouds mods, this is why it has conflicts. I need to tell git to stop this silliness, let me look it up.

**Comment by SpaceTeph** [comment]
And it's been a bumpy ride, but we're there.

**Comment by SpaceTeph** [comment]
@hakan42 whenever you're ready :D

**Comment by hakan42** [comment]
Yep, slightly busy with the man in the high castle, but in an hour or so :smile:

**Comment by SpaceTeph** [comment]
The build fails because, well, downloading the pack takes too long, but the packages are working. Could somebody please merge this?

**Comment by hakan42** [comment]
With the build failure, I can't merge this from my mobile. 

I should be at my pc within the hour, though, and will merge from there if no one beats me to it.

**Comment by SpaceTeph** [comment]
Many thanks! The task is now done for real :smile:

**Pull request merged**
