### PR TITLE
 Fill in missing author properties for failing ckans

### PR DESCRIPTION
**Pull request by DasSkelett**
See https://github.com/KSP-CKAN/CKAN/pull/3111, these ckans are missing the author property.
This PR adds it to those that fail validation, there's another one for those that validate successfully (#2108).

`grep -L "author" **/*.ckan`
```
RSSTextures2048/RealSolarSystemTextures_2048-1.0.ckan
RSSTextures4096/RealSolarSystemTextures_4096-1.0.ckan
RSSTextures8192/RealSolarSystemTextures_8192-1.0.ckan
RSSTexturesDDS2048/RSSTexturesDDS2048-1.0.ckan
RSSTexturesDDS4096/RSSTexturesDDS4096-1.0.ckan
RSSTexturesDDS8192/RSSTexturesDDS8192-1.0.ckan
```

### CODE REVIEW

**Comment by HebaruSan** [comment]
Maybe we should freeze these instead? Looks like @sarbian just doesn't host RSS textures anymore.

**Comment by DasSkelett** [comment]
> Maybe we should freeze these instead? Looks like @sarbian just doesn't host RSS textures anymore.

Good point. I had the "don't freeze modules they might be mirrored" though in mind, that's why I didn't think of freezing them. But since they aren't (otherwise the inflation wouldn't fail).

I'm gonna push another commit that freezes them, but keep the changes I already made, since it does no harm.

**Comment by sarbian** [comment]
Uh, did I delete something from my server ??

**Comment by HebaruSan** [comment]
@sarbian, the nathankell folder, probably about 5 years ago?

- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//2048.zip
- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//4096.zip
- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//8192.zip
- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//RSSTextures2048DDS.zip
- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//RSSTextures4096DDS.zip
- https://ksp.sarbian.com/nathankell/RealSolarSystem/Textures//RSSTextures8192DDS.zip

No big deal, we're just tidying up some old metadata.

**Pull request merged**
