### PR TITLE
Move old Toolbar releases to Dropbox downloads

### PR DESCRIPTION
**Pull request by politas**
Closes KSP-CKAN/NetKAN#4897

### CODE REVIEW

**Comment by politas** [comment]
That's odd. Jenkins is having a spaz over 1.7.9, which isn't changed by this PR.

**Comment by Olympic1** [comment]
Looks good, merging

**Comment by Nameaccepted** [comment]
so lets say im retarted and have no clue what this post is talking about

**Comment by politas** [comment]
The current release of Toolbar is on the author's server. As each new release comes out, the previous one is moved to a Dropbox folder. This change redirected CKAN to the Dropbox links for those earlier releases, so that people wanting to use older versions of KSP can still install the relevant version of Toolbar

**Comment by Nameaccepted** [comment]
well 3 days of screwing around with this. i give up. this is why i have never moded things

**Comment by Nameaccepted** [comment]
okay but i am having a lot more problems then the original post. every mod seems to error out

**Comment by politas** [comment]
Can you open a [new issue against the CKAN client](https://github.com/KSP-CKAN/CKAN/issues) and describe the errors you are getting in there?

**Pull request merged**
