### PR TITLE
AtmosphereAutopilot is compatible with 1.1.2

### PR DESCRIPTION
**Pull request by jreese**
Per KSP forum post: http://forum.kerbalspaceprogram.com/index.php?/topic/124417-112-atmosphereautopilot-153/&do=findComment&comment=2572523

### CODE REVIEW

**Comment by politas** [comment]
The online AVC .version file says it is compatible with 1.1.2, so this ought to have updated automatically. Since this is a netkan-generated ckan, any changes should be made there, but I'd like to leave this as an example of the larger issue.

**Comment by plague006** [comment]
@techman83 can you delete the cache for AtmosphereAutopilot please? That should resolve this particular mod.

**Comment by techman83** [comment]
@plague006 I removed the cache and triggered an index with no change.

**Comment by techman83** [comment]
Ok, found the issue. Not sure on the fix though. We're going to blat this even if it is changed. Doesn't happen for me locally though.

```
4062 [1] INFO CKAN.NetKAN.Transformers.AvcTransformer (null) - An error occured fetching the remote AVC version file, ignoring: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
4062 [1] DEBUG CKAN.NetKAN.Transformers.AvcTransformer (null) - Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, Boolean hasConverter) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) [0x00000] in <filename unknown>:0 
```

**Comment by techman83** [comment]
Fixed by upgrading Mono on the indexer. 813e36e1795eec3c645595524cb08b9f4aeffc52

**Pull request closed without merging**
