### PR TITLE
AVC support for KAS and KIS

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by dbent** [comment]
`$kref` and `$vref` placeholders are only usable by `.netkan` files, not `.ckan` files.

**Comment by plague006** [comment]
@dbent To the best of your knowledge is there an issue open (or closed) suggesting AVC version files that link to a static locations (as in the cases of KAS and KIS) can be scraped for updates and inflated into from netkans to ckans?

**Comment by dbent** [comment]
A HTTP `$kref` can be used by NetKAN and the version file will be used to populate version information. This is what's done for [`HyperEdit`](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/HyperEdit.netkan) and [`Graphotron`](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Graphotron.netkan).

But I believe Curse's terms prevent automatic scraping.

**Comment by plague006** [comment]
Good thing curse isn't involved then. =)

**Pull request closed without merging**
