### PR TITLE
Set ksp_version_max for old tweakscale versions

### PR DESCRIPTION
**Pull request by plague006**
Closes https://github.com/KSP-CKAN/NetKAN/issues/3522

### CODE REVIEW

**Comment by politas** [comment]
I have Tweakscale 1.5 in #1036, but I think yours might be better

**Comment by politas** [comment]
Hang on a bit, I'll undo my change to that file.

**Comment by plague006** [comment]
:+1:

**Comment by politas** [comment]
LGTM

**Pull request merged**
