### PR TITLE
Update and rename Fusebox-1.51.ckan to Fusebox-1.52.ckan

### PR DESCRIPTION
**Pull request by Ratzap**
new version

### CODE REVIEW

**Comment by politas** [comment]
Normally we would create a new .ckan file for a new version, so that people using older versions of KSP can access the versions built for them. Has this version been tested on on all 1.0.x versions of KSP? You're claiming that it will work on all of them.

**Comment by Ratzap** [comment]
This is the method I was asked to use when I started putting my mod in CKAN
(update and pull). If the preferred method has changed, are the steps
documented somewhere?

On 29 January 2016 at 09:16, Myk Dowling <notifications@github.com> wrote:

> Normally we would create a new .ckan file for a new version, so that
> people using older versions of KSP can access the versions built for them.
> Has this version been tested on on all 1.0.x versions of KSP? You're
> claiming that it will work on all of them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN-meta/pull/925#issuecomment-176655957>.
>



-- 
Ratzap
| Trust no-one, keep your laser handy, happiness is mandatory.
| German towns are, on average, about 10 Kilotons apart.
| Nuke 'em till they glow then shoot them in the dark.

**Comment by politas** [comment]
Since the preferred method is to use a netkan file to automatically grab new versions, I don't think there is a procedure written down somewhere. But if you look in the Fusebox folder, there are separate .ckan files for each version of Fusebox from 1.2 to 1.51

1.51 should only be for KSP 1.0.5, right?

Oh, and have you tried New BouncyBubbleBeverage, yet?

**Comment by politas** [comment]
Are you happy with #927?

**Comment by Ratzap** [comment]
Yeah I don't use netkan, I don't have Fusebox on github or kerbalstuff
which netan needs right?

1.51 is KSP 1.0.4, 1.52 is 1.0.5

Maybe talk to the CKAN team and add something to
https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN explaining
how to update a mod not hosted on github or kerbalstuff.

Good old Paranoia, I haven't slaughtered clones in years.

On 29 January 2016 at 14:49, Myk Dowling <notifications@github.com> wrote:

> Since the preferred method is to use a netkan file to automatically grab
> new versions, I don't think there is a procedure written down somewhere.
> But if you look in the Fusebox folder, there are separate .ckan files for
> each version of Fusebox from 1.2 to 1.51
>
> 1.51 should only be for KSP 1.0.5, right?
>
> Oh, and have you tried New BouncyBubbleBeverage, yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN-meta/pull/925#issuecomment-176792180>.
>



-- 
Ratzap
| Trust no-one, keep your laser handy, happiness is mandatory.
| German towns are, on average, about 10 Kilotons apart.
| Nuke 'em till they glow then shoot them in the dark.

**Comment by Ratzap** [comment]
This is fine yeah

On 29 January 2016 at 14:54, Myk Dowling <notifications@github.com> wrote:

> Are you happy with #927 <https://github.com/KSP-CKAN/CKAN-meta/pull/927>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN-meta/pull/925#issuecomment-176794705>.
>



-- 
Ratzap
| Trust no-one, keep your laser handy, happiness is mandatory.
| German towns are, on average, about 10 Kilotons apart.
| Nuke 'em till they glow then shoot them in the dark.

**Comment by politas** [comment]
Yes, Netkan requires a source that supports scraping. 
Ok, so #927 should be right for 1.52, and I'll have a look at the other versions to lock them down to the right KSP versions

**Comment by politas** [comment]
Thanks, Ratzap. I've merged the new file in #927, so I'll close this PR now. It's always good to get contributions from mod authors.

**Comment by Ratzap** [comment]
Indeed, no feedback, no change. Thanks

On 29 January 2016 at 15:14, Myk Dowling <notifications@github.com> wrote:

> Thanks, Ratzap. I've merged the new file in #927
> <https://github.com/KSP-CKAN/CKAN-meta/pull/927>, so I'll close this PR
> now. It's always good to get contributions from mod authors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN-meta/pull/925#issuecomment-176803174>.
>



-- 
Ratzap
| Trust no-one, keep your laser handy, happiness is mandatory.
| German towns are, on average, about 10 Kilotons apart.
| Nuke 'em till they glow then shoot them in the dark.

**Pull request closed without merging**
