### PR TITLE
Create Chopshop-0.6.5.ckan

### PR DESCRIPTION
**Pull request by doktorjet**
Update for 0.6.5

### CODE REVIEW

**Comment by Dazpoet** [comment]
Nice to see such a fine .ckan file! :)

You need citations around the spec_version and it should be `"v1.4"` and assuming 0.6.5 zip file has a similar folder structure as 0.6.5 an install stanza is required or CKAN won't find the right things. You can probably grab the install stanza from [here](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ChopShop/ChopShop-0.6.4.ckan).

I'm unable to find the 0.6.5 zip file on curse, it's not uploaded yet or? The download link will have to be a direct link to the .zip since curse has some download waiting time and our indexing bot can't handle that.

**Comment by doktorjet** [comment]
Hm-m-m... The reason for separate "install" instruction was the modulemanager.dll included in pack. It was excluded in 0.6.5. Should I still use "install"?

**Comment by doktorjet** [comment]
Failed with mirroring on GitHub... It's TOO complex comparing to TortoiseSVN I used when modding World of Warcraft. 
But I made a mirror on KerbalStuff. https://kerbalstuff.com/mod/709/Dr.%20Jet%27s%20Chop%20Shop
It should be easier to support in CKAN, right?

**Comment by Dazpoet** [comment]
KerbalStuff is indeed better. That means we'll put an auto-updating indexer linked to KS and you never have to care about it again unless the folderstructure changes in a way the indexing file can't handle.

The install stanza is so the indexing bot can always find the right folder. As you added it to KerbalStuff an automatic request was sent to our indexing repository [here](https://github.com/KSP-CKAN/NetKAN/pull/1005/files). It needs some fixing but is a much better solution than manual additions to CKAN-meta so I'll close this request and fix up the NetKAN one later based on this one :)

**Pull request closed without merging**
