### PR TITLE
update ExtraPlanetaryLaunchpads-RegolithAdaptation to .50

### PR DESCRIPTION
**Pull request by etam**

### CODE REVIEW

**Comment by mgsdk** [comment]
#rebuild

**Comment by Dazpoet** [comment]
Seeing as the mod seems to have changed direction and regolith no longer exists, should this have a new identifier or do we keep the old one?

**Comment by etam** [comment]
Uhm... Who is supposed to answer that question?

**Comment by Dazpoet** [comment]
Was hoping someone would pop out of the woodwork and give some feedback. I've been away for a while but just got my computer back up and running so I'll poke some people on irc about it. Sorry for the wait.

**Comment by etam** [comment]
So as I'm slowly learning CKAN i discovered NetKAN. So no matter what is the decision about identifier, this pull request should be declined and proper changes should be applied in NetKAN first.

**Comment by plague006** [comment]
If a mod has a new name and a new function it would seem like a new mod to me and I would expect a new listing for it. To back up my point: the KerbalStuff page isn't updated with the new mod/version and the KS page is also removed from the forum page.

**Comment by Dazpoet** [comment]
#rebuild

**Pull request closed without merging**
