### PR TITLE
Add MechJeb2-2.5.5

### PR DESCRIPTION
**Pull request by Olympic1**

### CODE REVIEW

**Comment by Olympic1** [comment]
@plague006 Help, the latest commit to the CKAN schema broke our bot

**Comment by Olympic1** [comment]
Fixed in [`f51329a`](https://github.com/KSP-CKAN/CKAN/commit/f51329ae053e12b54c4dcecf36701f0f9c93643a)

**Comment by plague006** [comment]
Back to normal/working?

**Comment by Olympic1** [comment]
Yes, the build passed this time without giving errors for the CKAN schema

**Comment by plague006** [comment]
:+1:

**Pull request merged**
