### PR TITLE
KSP Version Bump 1.0.4

### PR DESCRIPTION
**Pull request by Murdabenne**
metadata KSP version bump. Works, unchanged.

### CODE REVIEW

**Comment by SkyMarshal** [comment]
You should switch it to use `ksp_version_min` and `max`, otherwise people sticking with 1.0.2 will suddenly see it as incompatible.

**Comment by Murdabenne** [comment]
OK will do

**Comment by dbent** [comment]
`"ksp_version_min": "0.9"` should probably be `0.90`

**Comment by Murdabenne** [comment]
a trailing zero?  That's poor numeracy in the medical world where I come from, but OK.  Changed

**Comment by dbent** [comment]
Aye, but version numbers aren't decimals, they're integers separated by periods. "0.9" -> "Point-Nine", "0.90" -> "Point-Ninety".

**Pull request merged**
