### PR TITLE
Add ALCOR

### PR DESCRIPTION
**Pull request by plague006**
The capsule doesn't technically `depends` the IVA, but if not using the IVA the built-in Navigation, Dock port and Airlock lights won't work without an alternate mod library that we don't index (VNG Plugin). If someone wants to take up the mantle and include VNG Plugin then have VNG plugin and the IVA provide a virtual package and depend on that instead: by all means.

### CODE REVIEW

**Comment by plague006** [comment]
Jenkins fails because all 3 mods are interdependent.

**Comment by techman83** [comment]
@plague006 you may have to rebase once the new build script is merged. The inject process is supposed to take care of this. I'll test offline with the new script and see what happens.

**Comment by techman83** [comment]
Oh drat. My brain is having trouble switching between NetKAN + CKAN-meta. The current build process in CKAN-meta doesn't allow for this. I'll grab a coffee and see if I can port it across from NetKAN.

**Comment by techman83** [comment]
Ok this is now a thing. That was painful and now I'm covered in yak hair! Comit 2da5cda in KSP-CKAN/CKAN-meta#711

**Comment by techman83** [comment]
@plague006 I actually grabbed those files as my test case. Speaking of which I feel our build system may need tests. But then our tests for our build system may need tests.

xzibit

**Comment by plague006** [comment]
*sigh* me and rebasing..

It's branched off CKAN-meta if anyone wants to fix my gitting

**Comment by plague006** [comment]
See KSP-CKAN/NetKAN#1964 - 1996

**Comment by plague006** [comment]
I'll come up with some test cases within 24 hrs for you @techman83

**Comment by techman83** [comment]
@plague006 I mean automated ones :) - I've done a bunch of local testing. But being CI an really only visible to us we can probably get away with trial by fire for now.

**Pull request closed without merging**
