### PR TITLE
Get SamBelanger mods from archive.org

### PR DESCRIPTION
**Pull request by HebaruSan**
These mods have been removed from GitHub and SpaceDock.
This pull request updates them to download from the archive.org locations.

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by techman83** [comment]
LGTM and now passes :slightly_smiling_face:

**Pull request merged**
