### PR TITLE
Restrict KSP Version on obsolete KCT-RP0 Configs 

### PR DESCRIPTION
**Pull request by politas**
Ref KSP-CKAN/NetKAN#4348

### CODE REVIEW

**Comment by politas** [comment]
Hmm. Not sure why Jenkins isn't finding the 0.90 RP0 versions.

**Comment by politas** [comment]
@NathanKell , do you want to check and merge this?

**Comment by NathanKell** [comment]
LGTM but the build is failing. Wut do?

**Comment by politas** [comment]
Just merge it. Should be fine. We can fix any issues when people find them. I doubt there are many people still using 0.90 or older, and especially not trying to set up new configs.

**Pull request merged**
