### PR TITLE
InterstellarRedistributable should be compatible with KSP 1.8.1+

### PR DESCRIPTION
**Pull request by sswelm**
People with KSP 1.8.1 should be able to install the latest version of KSPIE

### CODE REVIEW

**Comment by sswelm** [comment]
not sure if this is correct but I want InterstellarRedistributable to be available for any KSP version higher than 1.8

**Comment by DasSkelett** [comment]
Hey, this will be overwritten by the bot as soon as it runs the next time. We either need to hardcode the compatibility in the [.netkan file](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InterstellarRedistributable.netkan) in KSP-CKAN/NetKAN, or you could include a version file like with KSP-IE.

**Comment by sswelm** [comment]
@DasSkelett I don't know how. I can't seem to be able to add version files to Version Checker

**Comment by DasSkelett** [comment]
Just like the one that is included for KSP-IE:
```
{
	"NAME":"Interstellar Redistributable",
	"URL":"http://ksp-avc.cybutek.net/version.php?id=XXXX",
	"DOWNLOAD":"https://spacedock.info/mod/2800/Interstellar%20Redistributable",
	"VERSION":
    	{
		"MAJOR":1,
		"MINOR":4,
		"PATCH":0,
		"BUILD":0
    	},
	"KSP_VERSION_MIN":
	{
		"MAJOR":1,
		"MINOR":8,
		"PATCH":1
	}
}
```

Just adjust the `NAME` and `VERSION`, and maybe upload a new remote version file to ksp-avc.cybutek.net and change the `URL`, or remove that property.

For hardcoding in netkan it's essentially the same as what you did here, just add a `ksp_version_min`, `ksp_version_max` is probably no longer needed nowadays (but if you fear Squad breaks their promise and _do_ release KSP 1.13 at some point, you could set max as well).

**Pull request closed without merging**
