### PR TITLE
Add KTwitter-1.1.ckan

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by pjf** [comment]
Aww, I was hoping this would actually let me tweet from KSP. :)

(I guess I can always write myself a KSP/exobrain bridge to let me do that...)

**Comment by plague006** [comment]
A crowd sourced science type of implementation into KTwitter would really elevate it to new levels. Invariably the tweets will become repetitive if there's only 1 writer.

**Comment by pjf** [comment]
I'd use machine learning (or just a markov chain) that's subscribed to all the tweets from the various landers, rovers, spacecraft, and crew in the system. I suspect we'd end up with some hilarious results.

Alas, I have no time to write software. :)

**Comment by plague006** [comment]
No worries I wasn't volunteering you to the task, just pointing out that no mod author could realistically write enough tweets for it not to be repetitive/boring/annoying.

**Comment by plague006** [comment]
Passes local, Jenkins fail is erroneous. Merging and adding to KSP-CKAN/CKAN#1273

**Pull request merged**
