### PR TITLE
Add GreeningGalaxy's Diverse Lasses

### PR DESCRIPTION
**Pull request by politas**
For @monstrim, since #1050 came so close

### CODE REVIEW

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
Installing from this CKAN, something very strange is happening. The zip file downloads, and then when it goes to install it, CKAN freezes. I can open the cached zip file with no problems and all the files are there.

**Comment by plague006** [comment]
Filter `.directory`. And yes I get the same error as Jenkins when trying to install this.

**Comment by politas** [comment]
@monstrim, is this your mod, or were you just wanting to see it in CKAN? It seems there may be something odd about the zipfile.

**Comment by monstrim** [comment]
It's not mine, I asked the author if I could add it here. I'll go see what I can do later, perhaps it's something about dropbox?

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
For whatever reason, it seems this mod is just not compatible with CKAN due to the author's zip file creation method.

**Pull request closed without merging**
