### PR TITLE
Removing Vanguard Astrodynamics library

### PR DESCRIPTION
**Pull request by Randazzo**

### CODE REVIEW

**Comment by plague006** [comment]
Explain what this is about?

**Comment by Randazzo** [comment]
Pretty self explanatory.

**Comment by plague006** [comment]
If it were, I wouldn't ask for an explanation.

**Comment by Randazzo** [comment]
I'm removing my library from ckan.

**Comment by plague006** [comment]
I don't see how that benefits users, can you explain that part?

**Comment by Randazzo** [comment]
Not saying it does, nor is it relevant.

**Comment by plague006** [comment]
Have there been any issues with installations or other issues CKAN has caused?

**Comment by Randazzo** [comment]
I've indulged you as far as I'm going to. Merge it or not.

**Comment by plague006** [comment]
I was hoping I could remedy any issues there may be between CKAN and you, but if you don't wish to continue discussing the matter I'll direct you to our [mod de-indexing policy](https://github.com/KSP-CKAN/CKAN/blob/652be658c931ea4e71d6e569d9a90c4b03021c55/policy/de-indexing.md).

**Comment by Randazzo** [comment]
Well done. You'll find the next versions released all rights reserved and your existing hosted versions are now no longer supported by me. Protecting those users, high five!
 

-----Original Message-----

**Comment by politas** [comment]
Have you included any contributions from other people in these mods? If so, you'll need their permission to switch to All Rights Reserved.

**Comment by plague006** [comment]
> You'll find the next versions released all rights reserved

Happy to hear we could help you find a license that accurately reflects how you want your intellectual property treated and regarded. As @politas pointed out sometimes there can be legal hurdles to changing to an ARR license but @pjf would happily help you navigate any issues if you should require it. I would offer my own help but my depth of knowledge in that area is lacking.

**Comment by Randazzo** [comment]
Clearly.

**Pull request closed without merging**
