### PR TITLE
Update KIS-1.27.ckan

### PR DESCRIPTION
**Pull request by Sinomen**
As per Ihsoft, when I asked if KIS 1.27 is compatible with KSP 1.10.1, he said "I assume it may not be compatible"

https://forum.kerbalspaceprogram.com/index.php?/topic/149848-minimum-ksp-version-111-kerbal-inventory-system-kis-v128/&do=findComment&comment=3898830

### CODE REVIEW

**Comment by DasSkelett** [comment]
Hm, wasn't the discussion about the minimum version though? I.e. it only works on KSP 1.11.0 (and potentially upwards)?

**Comment by Sinomen** [comment]
Darn, you are right, I DID both it up :(

**Comment by HebaruSan** [comment]
You should be able to edit again if you go to the [files changed tab](https://github.com/KSP-CKAN/CKAN-meta/pull/2235/files) and click the pencil icon again.

**Comment by DasSkelett** [comment]
Oh now worries, that's what PRs are for, so someone can review it and catch potential errors.

You can edit the file again similar to how you did before
(The pencil icon on this page: https://github.com/Sinomen/CKAN-meta/blob/patch-1/KIS/KIS-1.27.ckan).

Make sure you keep the "Commit directly to the patch-1 branch." option selected this time, so it goes to the same branch.

**Comment by Sinomen** [comment]
Done. Correct now?

**Review by DasSkelett — APPROVED** [review]
Yup, if I followed the discussion correctly, that's how it should be. Thanks a lot!

**Comment by HebaruSan** [comment]
:tada: 

image

**Comment by Sinomen** [comment]
Cool, and thanks a lot for your help! :)

**Pull request merged**
