### PR TITLE
Fix old mistakes

### PR DESCRIPTION
**Pull request by plague006**
Merge all linked netkan-related PRs first.

Closes https://github.com/KSP-CKAN/CKAN/issues/1755

### CODE REVIEW

**Comment by politas** [comment]
#rebuild

**Comment by techman83** [comment]
Looks like `beta` isn't a valid release_status according to our schema.
```
Failed validating u'enum' in schema[u'properties'][u'release_status']:
    {u'description': u'Optional release status',
     u'enum': [u'stable', u'testing', u'development']}

On instance[u'release_status']:
    u'beta'
Build step 'Execute shell' marked build as failure
```
I'd suggest it is valid :-)

**Comment by plague006** [comment]
Done

**Comment by techman83** [comment]
Oh, I meant I was going to go update the schema to allow beta. I don't think that field is used by the client anyway.

**Comment by politas** [comment]
The client does display it in the metadata tab.

**Comment by plague006** [comment]
@techman83: For the few users stuck on 0.90 I think we'd be best serving them by not requiring CKAN 1.18 to use a new beta status.

**Comment by techman83** [comment]
@plague006 aha, seems sane :+1:

**Comment by plague006** [comment]
Rebased again. If it looks good but it falls out of sync again just let me know and I'll merge manually.

**Comment by politas** [comment]
All the changes look fine to me. I'd say you're good to merge manually, though it's gonna be hard with that "cralwer" going.

**Comment by techman83** [comment]
@kspckan-crawler is nearly finished :laughing:

**Pull request merged**
