### PR TITLE
Adjustable Landing Gear works for 0.90

### PR DESCRIPTION
**Pull request by TeddyDD**
At least for me and everybody who was clever enough to update Firespitter plugin :sunglasses: 
Tested

### CODE REVIEW

**Comment by TeddyDD** [comment]
I have no idea why its fails :sos:

**Comment by hakan42** [comment]
1137 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on BDAnimationModules found, but nothing provides it.
Module BDAnimationModules required, but not listed in index, or not available for your version of KSP

**Comment by TeddyDD** [comment]
Yeah I saw that. Look into Files changed. I set ksp_max_version for BDAnimationModules too. CKAN should be able to use it

**Comment by hakan42** [comment]
Timing issue. First, the BDAnimation needs to be available through the normal metadata (meaning, a separate PR which needs to be merged first).

Then, you can base the Landing Gear on it.

Best to keep things well-separated :smiling_imp:

**Comment by TeddyDD** [comment]
rrr

**Comment by TeddyDD** [comment]
Second PR ready, waiting for first one to merge

**Comment by hakan42** [comment]
Merged with comments :smiling_imp:

**Comment by TeddyDD** [comment]
<facepalm> This is not a good day for me to think :Z
Ok, I'm going to netkan now

**Pull request closed without merging**
