### PR TITLE
Update Kartographer-1.1.0.ckan

### PR DESCRIPTION
**Pull request by Real-Gecko**
satnet is the original author.

### CODE REVIEW

**Comment by HebaruSan** [comment]
The bot reverted this based on the data pulled from SpaceDock. Can you add multiple authors there?

**Comment by Real-Gecko** [comment]
Hmmm, I guess I needed to fix this on NetKAN part just like I did with [NoCrewRequirementContinued](https://github.com/KSP-CKAN/NetKAN/commit/c239f482f2c12820f88bbbc31e299b60298b2cef#diff-1480651bafdc4e89afe2dbd9f2a82ac7). That did not cause any troubles even though Orbinaut was never registered on SpaceDock.
So, do we cancel this request and create a new in NetKAN repo? Will this work?

**Comment by HebaruSan** [comment]
> So, do we cancel this request

That isn't necessary; you can just ignore this pull request, as it was already merged.

> and create a new in NetKAN repo? Will this work?

Yes, I believe so.

**Comment by Real-Gecko** [comment]
Did that https://github.com/KSP-CKAN/NetKAN/pull/6013

**Pull request merged**
