### PR TITLE
Add KerBalloons 0.3.1

### LINKED ISSUE #931: KerBalloons v0.3.1 - CKAN File
Here is the CKAN file

[KerBalloons-v0.3.1.zip](https://github.com/KSP-CKAN/CKAN-meta/files/112827/KerBalloons-v0.3.1.zip)

### PR DESCRIPTION
**Pull request by Olympic1**
Fixes #931

### CODE REVIEW

**Comment by politas** [comment]
I thought NetKAN couldn't handle curseforge releases?

**Comment by Olympic1** [comment]
we can but not automatically, dropbox and curse we need to do manually

**Comment by politas** [comment]
Ok. What's the process to get a NetKAN-generated CKAN for a Curseforge release?

**Comment by Olympic1** [comment]
Well I type all the basic stanzas to begin with (spec, id, version, install, mod info, ...) and then add the `download` stanza with the dl link and generate a `.ckan

```
{
     "spec_version": 1,
     "identifier": "KerBalloons",
     "name": "KerBalloons",
     "abstract": "Adds various balloons to KSP",
     "author": "JoePatrick1",
     "license": "restricted",
     "resources": {
         "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/107432-105-kerballoons-v031-balloons-for-ksp/"
     },
     "version": "v0.3.1",
     "ksp_version": "1.0.5",
     "install": [
         {
             "file": "KerBalloons",
             "install_to": "GameData"
         }
     ],
     "download": "http://kerbal.curseforge.com/projects/kerballoons-v0-3-1/files/2279478/download",
 }
```

**Comment by politas** [comment]
Thanks. That seems clear. I might put together a NetKAN howto page some time.

**Pull request merged**
