### PR TITLE
HeatManagement and VanguardAstrodynamicsVXSeries to spacedock downloads

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by Olympic1** [comment]
:+1:

**Comment by Randazzo** [comment]
It's amusing to see you're going out of your way to go against my wishes just so you can have outdated and unsupported versions of my mods on CKAN. If I get any support requests for these, I will direct them to you two on the forums.

**Comment by Olympic1** [comment]
@Randazzo, If you would maybe tell us why you want to remove the metadata from CKAN, we can understand and help you.

Did we do something wrong, are your mods being wrongly installed. It doesn't help us if you just make a PR to delete everything from your mods without any explanation.

**Comment by politas** [comment]
There are a lot of outdated and unsupported mods on CKAN. A mod being on CKAN is no indication that it will be supported by the mod author.

**Comment by Randazzo** [comment]
I will be quoting you on this.
 
 
-----Original Message-----

**Pull request merged**
