### PR TITLE
Fix InterstellarFuelSwitch depends

### PR DESCRIPTION
**Pull request by HebaruSan**
Historical version of KSP-CKAN/NetKAN#7883 and KSP-CKAN/NetKAN#7884.

 KSP-CKAN/NetKAN#4016 said:

>IFS is heavily integrated with Tweakscale and it relies on very specific functionality from Tweakscale to work correctly when installed

However, it added TweakScale as a recommendation, not a dependency. This means users can de-select it during install and thereby stop IFS from working correctly.

Now it's a depends going back to IFS-Core 2.3.1.

Also in 3.13.0.5 CommunityResourcePack was removed and CommunityTechTree was bundled. Now that's in the metadata too.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hmm, this may need to be filtered out:

```
- GameData/InterstellarFuelSwitch/Plugins/Scale_Redist.dll
```

**Comment by HebaruSan** [comment]
I think we finally used up all our CPU credits. If it fails again, I'll wait a couple of hours before trying again.

**Comment by techman83** [comment]
Yep, seems pretty spent!


We should have a think about our testing procedure at some point. We do have an instance sitting there doing next to nothing for quite a long time, then bursting for short periods.

**Comment by HebaruSan** [comment]
Yeah, it mostly seems to trip up on these PRs with dozens of files. I'd like to make it run the validation for ALL the files in a PR, continuing on even if one fails, and then report whether there were any failures at the very end. That would identify more problems in fewer passes, since we could go through and fix 5 or 6 things per commit.

**Pull request merged**
