### PR TITLE
Don't use "GPOSpeedFuelPump"; correct CKAN identifier is "Goodspeed"

### PR DESCRIPTION
**Pull request by henrybauer**
Due to a lot of confusion, there's two GPOSpeedFuelPump entries, and it's causing confusion.  See https://forum.kerbalspaceprogram.com/index.php?/topic/137489-16-gpospeedfuelpump-continued-v1818/&do=findComment&comment=3582515

image

I've asked for the NetKAN file to be fixed in https://github.com/KSP-CKAN/NetKAN/pull/7123

This change is to modify the CKAN-meta entries.  I believe we want to leave these entries so that people can uninstall, but they should be warned that it's not the right one to install.

### CODE REVIEW

**Comment by DasSkelett** [comment]
I would remove the "zzz" in front of the name, this just interferes with the mod list sorting. The "Do not use" should be enough.
Additionally, I think we could add our new "replaced_by" relationship here.

**Comment by DasSkelett** [comment]
Do I understand correctly that those 7 versions are also available in `Goodspeed`?
We could freeze, or maybe even delete those .ckans.
You can still uninstall them properly afterwards.

**Comment by henrybauer** [comment]
> Do I understand correctly that those 7 versions are also available in `Goodspeed`?

Yes.  I've updated their .ckan files now.

> We could freeze, or maybe even delete those .ckans.
> You can still uninstall them properly afterwards.

Oh cool, that works too.  I've deleted these files instead.

**Comment by DasSkelett** [comment]
Last commit was to resolve a merge conflict resulting from https://github.com/KSP-CKAN/NetKAN/pull/7123

**Pull request merged**
