### PR TITLE
Confirmed mods working in 1.0.3

### PR DESCRIPTION
**Pull request by jrossignol**
Not re-releasing said mods at present, so updating CKAN-meta directly.

### CODE REVIEW

**Comment by pjf** [comment]
If these are being indexed by netkan then our bots might overwrite them unintentionally. Checking now, update in a minute. :)

**Comment by jrossignol** [comment]
Bleh, they are indexed by netkan. :cry: 

Basically, I didn't want to re-release said mods just to update the .version file (since KSP-AVC will override the in-game popup with whatever it pulls from the URL in the .version file instead of what's actually in the .version file).

Anyway, not a huge deal...  it's just a pain to update every time KSP updates. :wink:

**Comment by pjf** [comment]
Oooh! This *is* interesting! Some (possibly all) of these mods have embedded `.version` files. We love respecting those, because it means mod authors can exactly specify which versions they target.

Except in cases like this, where no new release should be necessary, but the metadata should be updated.

Options we might choose could be to simply to disable indexing for these mods until the next release, but that comes with the risk that we might forget to turn them on. Or we could update the .netkan file to include the new info, but that means we wouldn't look at the the `.version` file in new releases. Neither of those feel like good solutions.

I think our best solution is to update `netkan.exe` so that we can add version-specific directives, something like:

```
"x_netkan_override" : {
    "version" : "1.4.2",
    "overide" : {
        "ksp_version_min" : "1.0.0",
        "ksp_version_max" : "1.0.3"
    }
}
```

Then if we see that precise version of a mod being released (which includes reindexing what we already have) then we can change what we spit out. If we see any other version we ignore the override and proceed as normal.

We don't have this yet (but I'm about to open a ticket so we will). In the meantime, are you happy if we stop auto-indexing these mods (so we can preserve the changes in your PR), and then turn the indexer back on for new releases? (You may need to remind us when this happens.)

**Comment by jrossignol** [comment]
I'd prefer not to disable indexing - as I'm likely to forget to notify you to turn it back on.

Instead, how about this - merge the PR, and I'm going to go and update the .version files in my releases on GitHub.  That way even if stuff gets overridden, it'll still have what I want.  There might be one user in a million that's actually checking md5 sums or something that'll notice that the release got changed....  more power to them I guess.

The netkan override sounds nice...  but not sure how many mod authors will make use of it.  Still, the more Squad releases these little hotfix patches, the more this becomes an issue, so I guess it's good to have the tools available to deal with it.

**Comment by pjf** [comment]
@jrossignol : Ticket opened for per-version overrides anyway; I think it's something that would be really useful for us in the future (although it solidly targets our indexing team rather than the average mod author).

Updating the `.version` files inside the releases on github sounds like it would work splendidly.

So merging this now as your request, although be aware that if our indexer looks at your releases before they're updated, it's liable to change them back. (And will then change them forward again once it sees the embedded `.version` updates.)

Many thanks again!

**Comment by jrossignol** [comment]
Already done, the indexer never had a chance.

**Comment by techman83** [comment]
@jrossignol - you had bit over an hour to spare :)

**Comment by jrossignol** [comment]
Sadly, netkan overwrote my changes anyway - perhaps it has a local copy of the .zip file cached?  I suspect the best way to deal with this without having to mess with the .netkan file (which I'd prefer not to do if it means reverting it later) is just to cut new releases of my stuff.  Which is a major pain when Squad is releasing hotfixes every other day...

**Comment by jrossignol** [comment]
Hmm....  scratch that, it only overwrote one of them - maybe I messed that one up.

**Comment by techman83** [comment]
@jrossignol - You are quite right, to save belting the hosts downloading the Zip files on every run they are indeed cached. Let me go sort that out so it grabs the new zip file on the next run.

**Comment by techman83** [comment]
@jrossignol, is done. It'll pull the latest zip on the next run.

**Comment by pjf** [comment]
Thank you all so very much for this. Of course our bots cache their downloads locally, and yet I totally didn't consider that yesterday.

**Comment by techman83** [comment]
@pjf - It didn't initially cross my mind and I've been herding them :)

**Pull request merged**
