### PR TITLE
De-lists FerramAerospaceResearch.

### PR DESCRIPTION
**Pull request by Ippo343**
The author has asked multiple times for this to be done.
Yes, this PR violates the project's policy on de-indexing.

However, I object to the policy because the mod's license cannot possibly apply to CKAN's metadata (as our metadata files are install instructions, they are not covered in any way by the redistribution clauses of the mod). Thus, I believe that forcing a mod in the indexed by virtue of a license that cannott apply to the metadata is unfair.

### CODE REVIEW

**Comment by TeddyDD** [comment]
Personally I'm against this. Whining of modder should not be confused with license of a mod.

 However if you insist there is one problem. I suppose some mods depends on FAR like AdvancedJetEngine, Trajectories, also most stuff from RealismOverhaul. This mod will have to be removed from CKAN.

Plenty of mods suggests and recommends FAR. I'm not sure about CKAN.exe behavour but I suppose those relations will have to be removed.

**Comment by Ippo343** [comment]
I believe that the license of the mod doesn't apply to our metadata. We are not distributing anything so distribution clauses do not apply in any sense to ckan.

Because of this, I don't think we should make any distinction between mods based on their license. In my opinion, any modder that wants his mod delisted should have it.

I mainly made this PR to raise the issue. I believe that our delisting policy is wrong as it stands, because it's based on the false premise that we are bound by the mods' license which in reality don't apply to us.

I still remember the early days where I personally contacted tens of authors to ask them their permission to include them.
My message explicitly said that we wouldn't be including their work if they didn't give us their permission.
Let's go back to that spirit.
________________________________
Da: Daniel Lewan<mailto:notifications@github.com>
Inviato: ‎24/‎06/‎2016 23:43
A: KSP-CKAN/CKAN-meta<mailto:CKAN-meta@noreply.github.com>
Cc: Michele<mailto:m.ippolito@outlook.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [KSP-CKAN/CKAN-meta] De-lists FerramAerospaceResearch. (#1184)

Personally I'm against this. Whining of modder should not be confused with license of a mod.

 However if you insist there is one problem. I suppose some mods depends on FAR like AdvancedJetEngine, Trajectories, also most stuff from RealismOverhaul. This mod will have to be removed from CKAN.

Plenty of mods suggests and recommends FAR. I'm not sure about CKAN.exe behavour but I suppose those relations will have to be removed.

---

**Comment by TeddyDD** [comment]
Related https://github.com/KSP-CKAN/CKAN/issues/1793 https://github.com/KSP-CKAN/CKAN/issues/1078

>We are not distributing anything so distribution clauses do not apply in any sense to ckan.

I agree that license don't apply to metadata itself but CKAN its not only metadata. `ckan.exe` could be interpreted as form of distribution or not. I'm not a lawyer :cop: 

>Let's go back to that spirit.

I think that policy described by @pjf in https://github.com/KSP-CKAN/CKAN/issues/1078 is pretty reasonable and should not be changed.
 Instead of this we should focus on making CKAN less annoing for modders. (Example: add unsupported flag that would show warning when mod is installed: "You wont get any support if you install XYZ mod via CKAN!!!!1". Big red flashing font, you know :red_circle:  )

**Comment by anxcon** [comment]
@TeddyDD problem with that is people are *bleep* and if they install a mod, they cry to the mod author, to the user that is all they see, i don't blame them for that, nor would i ever expect improved behavior by the user, it is what it is

if ckan removes the downloading bit, but keeps the update checks, link to forums post of the mod / maybe even some steps to manual install easier on user / but still more than single click done, i would foresee less issues. at that stage it is more like forum posts just compiling a list to all mods in the forum, which ive never seen complaints at unless someone changes thread but hey that bit is rare :)

in the end, "legal" isnt the only thing people have to consider. just because you can legally do things, doesnt mean you should. modding communities have morales, and so far the only thing i find toxic in ksp community is ckan stance towards mod authors.

lastly, forcing mods to go ARR is not always possible, especially when a mod to be used with other mods / and its framework expanded upon. ckan abuses that even that niche, further proving the lack of morale standing to the community

**Comment by TeddyDD** [comment]
After reading some stuff here http://forum.kerbalspaceprogram.com/index.php?/topic/142358-ckan-discussion-continutation/&page=2 I found few interesting ideas

We could try something like Arch offical / aur repos. Official repo (enabled by default) would be opt-out for modders. Unsupported repo could contain everything else but it would have to be activated manually. It would also show warning about lack of support from mod autors.

**Comment by anxcon** [comment]
@TeddyDD again, users don't pay attention to anything relating to support or lack thereof. if "unofficial" repo exists, people will use it as the primary as it has everything and more, then assume all issues after that point belong to the mod author. 

the issues with ckan, ksp modding, etc, have been dealt with in other communities. none of this is new. so there isn't really a reason to re hash flawed systems IMO, use well established and stable systems, respect mod authors for the free toys they provide, work with the author, and everyone is happy.

**Comment by ferram4** [comment]
As it turns out, FAR has some art and shader assets that only I have contributed to.  As such, it is in my power to re-license them ARR and the next FAR release shall have them licensed as such.  Exactly as asked by CKAN contributors, I shall license FAR more restrictively.

Now, my position with respect to de-listing has always been that the request should be rescinded the second CKAN allows courtesy de-listing and takes steps to ensure that metadata errors are simply not as common.  As long as I have a way to reduce the support load that CKAN creates if CKAN completely fails at its job or fails to react to issues that affect modders in a timely fashion, I don't mind CKAN indexing my mods.

However, I realize that those conditions are unlikely to happen quickly, and the chaos caused by a straight de-listing the second the more restrictive FAR is uploaded will introduce unnecessary drama and workload for users and other mod authors.  So, with that context established, as a show of goodwill, **I would like the de-list request closed when the more restrictively licensed FAR is released**.

And with things set up like that, we can have an amicable discussion about CKAN's policies and their consequences.

**Comment by Blu3wolf** [comment]
> I believe that the license of the mod doesn't apply to our metadata. We are not distributing anything so distribution clauses do not apply in any sense to ckan. Because of this, I don't think we should make any distinction between mods based on their license. 

All perfectly reasonable.

> In my opinion, any modder that wants his mod delisted should have it.

Except that part. I like the idea above, of having an indication to users that a mod is unsupported by the author if installed via CKAN. Possibly another click through screen in the GUI, along the lines of: 'The following mods are unsupported by the author unless manually installed'.

**Comment by anxcon** [comment]
@Blu3wolf users dont read, users click and go, i highly suggest a job in the IT support direction, if only for a week, you learn many things, and its entertaining

users see button to install, they click, thats the end of ckan role, to them they only see mod broke, tell author - you can claim they are in the minority all you want, and are "ruining it" for the mature peeps, said claim doesnt stop it

**Comment by Blu3wolf** [comment]
@anxcon did that for a while, got the usual entertaining stories out of it (computer doesnt work - have you tried plugging it in? no...). 

If modders have a problem with incomplete bug reports, thats hardly the fault of CKAN, for making their mod more accessible.

**Comment by TeddyDD** [comment]
@politas This can be merged now as well. Without ModuleManager FAR is useless.

**Comment by ferram4** [comment]
And yet, that would be contrary to my wishes.  If CKAN is to continue with the adjusted policy, I see no reason to actually de-list FAR or any of my mods.  Leave everything as is until the smoke has cleared, since it will likely be easier in the long run.

**Comment by Blu3wolf** [comment]
Thats not necessarily a small 'if'.

**Comment by ferram4** [comment]
Of course not.  Yet one that should be acknowledged because the lowest-unnecessary-workload option right now is to "wait and see" on how things turn out.

**Comment by ferram4** [comment]
And with https://github.com/KSP-CKAN/CKAN/pull/1795 merged, the main reason for my protest-request for de-listing has been met.  I see no reason to de-list at this point, and would like to request that this PR be closed.  Thanks @Ippo343 for starting it, but everything should be cool now.

**Comment by politas** [comment]
Thanks @ferram4  Closing.

**Comment by Blu3wolf** [comment]
> 
> 
> As it turns out, FAR has some art and shader assets that only I have contributed to. As such, **it is in my power to re-license them ARR** and the next FAR release shall have them licensed as such. Exactly as asked by CKAN contributors, I shall license FAR more restrictively.


As a funny aside, this is not actually the case. The versions of those art and shader assets which you released previously under the GPLv3 remain GPLv3 - the license is **irrevocable**, sorta a key point for the GPL. To prevent authors from holding their works to ransom. 

Your textures havent changed since you stopped licensing them under GPLv3, so those textures are actually up for anyone else to use - so long as THEY comply with the terms of the GPLv3. I do note that you have made changes to your farshaders.ksp file since the March 8, 2016 version, so those later versions are ARR, but the prior ones are still up for grabs under GPLv3.

**Pull request closed without merging**
