### PR TITLE
RCSBuildAid version 0.7

### PR DESCRIPTION
**Pull request by m4v**
I'm not familiar with the spec, I just copied and edited the relevant stuff.

### CODE REVIEW

**Comment by RichardLake** [comment]
Since you use github and avc you could create a netkan file which would automatically generate the ckan files with each release. However that would use the github release api which does not seem to work with your repo. https://api.github.com/repos/m4v/RCSBuildAid/releases

**Comment by m4v** [comment]
I need to do a release in github for it to show in its API, I just use it as a repository. As I understand, for that netkan thingy to work I will have to manually do a release in github with a  zipped binary and all that. 

Either way I need to do something for get ckan to pick it up.

**Comment by Dazpoet** [comment]
Please filter the Sourcecode out, we don't normally install that.

**Comment by m4v** [comment]
how do I do that?

**Comment by Dazpoet** [comment]
in the install stanza add a `"filter" : "Sources"` so it becomes 
```
"install": [
       { "file" : "RCSBuildAid", "install_to" : "GameData", "filter" : "Sources" }
    ]
```

That should filter the entire `Sources` folder.

**Comment by m4v** [comment]
done

**Comment by Dazpoet** [comment]
Thank you :D

**Pull request merged**
