### PR TITLE
KerbinShuttleOrbiterSystem-4.2.ckan

### PR DESCRIPTION
**Pull request by Nazari1382**
I dont know what to do with my hands

### CODE REVIEW

**Comment by RichardLake** [comment]
Hi. Could you change the syntax for the author field? It should be "author" : ["nazari", "helldiver"],

**Comment by Dazpoet** [comment]
Filename, foldername and identifier must be identical (but the version is added to the filename). Also maybe this should be added through NetKAN instead as an update of https://github.com/KSP-CKAN/NetKAN/pull/1279 ? That way no need .ckan file will have to be generate each time a new release is put onto KS.

**Comment by Nazari1382** [comment]
Does this work? I'm new to Github...

https://github.com/KerbalStuffBot/NetKAN/pull/5

I want it to auto update from Kerbalstuff, but want it to keep whatever dependency changes I make on here. The other copies of KerbinShuttleOrbiter can be removed from ckan.

**Comment by mgsdk** [comment]
I believe you want to make the PR against https://github.com/KSP-CKAN/NetKAN (The repository it was originally forked from and used by CKAN) instead of https://github.com/KerbalStuffBot/NetKAN.

**Comment by Dazpoet** [comment]
superceded by https://github.com/KSP-CKAN/NetKAN/pull/1298 so I'm closing this.

**Pull request closed without merging**
