### PR TITLE
Move NavUtils to Github download

### PR DESCRIPTION
**Pull request by politas**
Only source remaining for this mod.

### CODE REVIEW

**Comment by politas** [comment]
This ought to let KSP-CKAN/NetKAN#3407 build cleanly.

**Comment by Dazpoet** [comment]
Somewhat tired but the errors seem to be Jenkins being even more tired than me. Either way an existing link which installs something is objectively better than a non-existing and non-working link :+1:

**Comment by techman83** [comment]
Hmm, not sure why it is testing the things it is testing.
```
CKAN.FileNotFoundKraken: Trying to install SteampunkColorCodedSpaceSuits 2, but it's not downloaded or download is corrupted
```

**Comment by politas** [comment]
Yes, I've been getting increasingly exasperated with the CKAN-meta build testing.

**Comment by techman83** [comment]
Yeah, sounds like it needs some attention. From a quick look it's testing things outside the set of commits it's supposed to be doing. Not sure what's changed to cause this though.

**Comment by politas** [comment]
It's been doing that for some time (as in weeks at least, if not months)

**Comment by techman83** [comment]
Or forever. PR incoming.

**Pull request merged**
