### PR TITLE
Assorted Promiscuity Fixes

### PR DESCRIPTION
**Pull request by politas**
Making some old mod versions no longer appear as compatible with KSP1.1

### CODE REVIEW

**Comment by plague006** [comment]
Thanks, should have looked at this sooner. I'm reviewing it now and the only thing standing out is:
For `AGroupOnStage` the download is changing? And we're turning compatibility backward?

**Comment by politas** [comment]
Yes, I should have added some details on that one. The version number is a mistake, it should have been 2.0.9.1 not 1.0.9.1. Setting the compatibility and download will make that older version I found on Github accessible.

**Comment by plague006** [comment]
I had a bit more time today to look into it.. basically `AGroupOnStage-1.0.9.1` is a dead link at the moment, but why aren't you just deleting it?

Your PR is going to label what is actually `v1.0` of the mod under the label of version `1.0.9.1`? Why wouldn't you just modify the `version` and filename to accurately represent that this is v1.0? Further if you're going to retroactively index a mod for ksp 0.24.2 why wouldn't you use the most up-to-date version known to be compatible with that ksp version (ie. AGroupOnStage V1.2 for KSP 0.24.2)?

**Comment by politas** [comment]
Because currently people have in their CKAN this number 1.0.9.1, and it's horrendously promiscuous. We need to change that in people's CKAN clients. This should basically make it disappear.

**Comment by plague006** [comment]
> We need to change that in people's CKAN clients.

There are 2 parts to a user's local metadata. If a mod is installed, then that metadata remains until a mod is uninstalled (or updated). If a mod isn't installed, then the metadata is wholly rewritten every time they hit refresh. There's never a good reason to give users bad metadata.

**Comment by politas** [comment]
Ok, deleted.

**Comment by plague006** [comment]
:+1:

**Pull request merged**
