### PR TITLE
Give ksp version compatibility caps to Solver Engines and Animate Emissives

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by Dazpoet** [comment]
The version file in https://github.com/KSP-CKAN/NetKAN/pull/2191 dets ksp_version to strict 1.0.4 so if a 1.0.5 comes out users will get these versions rather than the latest one, would it periapsis be advisable to have these as ksp_version_max 1.0.4?

**Comment by Dazpoet** [comment]
I hate autocorrect but I hope the message came through!

**Comment by plague006** [comment]
Done, for the 1:100,000 chance that 1.1 isn't the next release.

**Comment by techman83** [comment]
aws-stats

Munch munch munch. Looks like Jenkin's chewed through that lot! :+1:

**Pull request merged**
