### PR TITLE
Rename Asclepius-clouds-v1.1.ckan to Asclepius-clouds-1.1.ckan

### PR DESCRIPTION
**Pull request by politas**
Another one that a file rename might fix. Worth a try, anyway, since it's the least disruptive option.

### CODE REVIEW

**Comment by plague006** [comment]
As https://github.com/KSP-CKAN/CKAN-meta/pull/860 changing filenames will have no effect.

**Comment by politas** [comment]
I worry with these that people who have installed "v1.1" will be unable to update, ever.

**Comment by plague006** [comment]
You're right that users of v1.1 cannot upgrade to 1.2 however the solution you're attempting will not accomplish that goal.

When a user installs a mod they basically create a local copy of the metadata for that mod, so even if we change v1.1 to 1.1 their local metadata will always remain v1.1 until they uninstall or upgrade the mod. So because v1.1 is a higher version than 1.2 (according to CKAN) how do we allow the upgrade? Epochs. Setting an epoch of "1" in the netkan will create `1:1.2` which is a higher version than both v1.1 and 1.2. (As an aside we'll actually be creating `1:v1.2` since we're going to use an epoch *and* force_v.

**Comment by politas** [comment]
Ok. That makes sense.

**Pull request closed without merging**
