### PR TITLE
Update KerboKatzUtilities-1.5.2-KSP1.8.ckan

### PR DESCRIPTION
**Pull request by Homer-S**
Correct for new maximum version 1.8.x of KerboKatzUtilities.

### CODE REVIEW

**Comment by HebaruSan** [comment]
This PR wouldn't work because the bot would overwrite it with the upstream source data, which is owned by the author, fix submitted in KerboKatz/Netkan#11.

**Comment by Homer-S** [comment]
What confuses me on these is that the content of the .ckan does not match what is upstream. There do not appear to be versions ending in -KSP1.8 on the upstream netkan.

**Comment by HebaruSan** [comment]
> There do not appear to be versions ending in -KSP1.8 on the upstream netkan

Here they are:

https://github.com/KerboKatz/KerboKatzUtilities/releases

**Comment by Homer-S** [comment]
Thanks... I see the new version but how is that reflected in [their netkan](https://raw.githubusercontent.com/KerboKatz/Netkan/master/AutomatedScienceSampler.netkan) from which the .[ckan ](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AutomatedScienceSampler/AutomatedScienceSampler-1.3.5-KSP1.8.ckan)is created. Could just be me missing something.

**Comment by DasSkelett** [comment]
NetKAN takes the tag of the github release as mod version.
A new release with the tag `1.5.2-KSP1.8` will be indexed as mod version ` 1.5.2-KSP1.8`.

**Comment by Homer-S** [comment]
I see... so there is one additional change that the non-utilities mods need. The dependent version for KerboKatzUtilities should be 1.5.2-KSP1.8 and not just 1.5.2. I'll submit that to the upstream spot. Thanks for the patience and increasing my understanding!

**Pull request closed without merging**
