### PR TITLE
Normalize historical install_to paths

### PR DESCRIPTION
**Pull request by HebaruSan**
See KSP-CKAN/CKAN#2880; KSP-CKAN/NetKAN#7419 repaired affected netkans, this PR fixes historical metadata.

### CODE REVIEW

**Comment by HebaruSan** [comment]
```
Validating metadata: 'KerbalAircraftExpansion/KerbalAircraftExpansion-v2.3.3.kerbalstuff'
101302 [1] FATAL CKAN.NetKAN.Program (null) - The operation has timed out.
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
```
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USI-Core 0.1.8.0
Owning Mod     : USITools
CKAN Version   : v1.26.5+d79c04a47bde

Your GameData has been returned to its original state.
```

**Comment by DasSkelett** [comment]
Oh wow, how did you find that issue ^^

**Comment by HebaruSan** [comment]
I...
- clicked that link,
- [changed `raw.githubusercontent` to `github` and added `blob/` before `master` in my  URL bar](https://github.com/BobPalmer/CKAN/blob/master/USI-Core.netkan),
- then [clicked History to see the commits](https://github.com/BobPalmer/CKAN/commits/master/USI-Core.netkan),
- [clicked "USI-Tools/USI-Core conflicts - don't overwrite FX"](https://github.com/BobPalmer/CKAN/commit/b8ae04550655e99ff054699da0a7dc9ea78f1791#diff-71618ee6ff559251657ae5900e7171f5) since it sounded promising,
- then saw the issue referenced in the header.

And now I've learned that if I type "commits" instead of "blob", I can skip a step.

**Pull request merged**
