### PR TITLE
update Hyperedit for 1.4.1

### PR DESCRIPTION
**Pull request by Blu3wolf**

### CODE REVIEW

**Comment by Dazpoet** [comment]
Are those flags part of all Kerbaltek mods now? If so we might have to filter them as to not have them conflicting with eachother.

**Comment by Blu3wolf** [comment]
Sorry, which flags are you referring to? Im a bit lost sorry.

**Comment by Dazpoet** [comment]
The ones installed to `GameData/Kerbaltek/Flags` which come with this mod.

**Comment by dbent** [comment]
> Are those flags part of all Kerbaltek mods now? If so we might have to filter them as to not have them conflicting with eachother.

The other Kerbaltek mod, `Graphotron` doesn't contain the flags as of now.

Also, I'm surprised this .ckan works, if you try to download directly from a browser the server will throw back the response `DOWNLOADER: Sorry, no direct access.` because no `Referer` header is sent with the request. Does CKAN actually send a `Referer` with its requests?

**Comment by Dazpoet** [comment]
I'd say you're better off asking a dev on irc (I assume you're zengei @dbent?). For now I'll merge this since it seems to be working :)

**Comment by dbent** [comment]
> I assume you're zengei @dbent?

Aye, that's me.

**Pull request merged**
