### PR TITLE
Add ModularFuelSystems 5.7.4

### PR DESCRIPTION
**Pull request by politas**
Closes KSP-CKAN/CKAN#1719

### CODE REVIEW

**Comment by plague006** [comment]
Want to add?
````
    "download_hash": {
        "sha1": "C52E0DC8B469307FCF3B8E37795CD04B3B146C26",
        "sha256": "D3FE1C710E5F60C3AE25F7E0B5FA3BB40D3E21E99DE163743AC63D5271C5E955"
    },
    "download_content_type": "application/zip"
````

**Comment by plague006** [comment]
Bah whatever, I'll work on this once netkan pushes non-kref ckans.

**Comment by politas** [comment]
All future ones will have that stuff.

**Comment by techman83** [comment]
We'll need to go back-fill that data anyway, so no biggie if things aren't there yet. Though I thought we were moving to doing everything in NetKAN now (which would add that).

**Comment by plague006** [comment]
I didn't think we could move forward on that. I was under the impression .netkans not having a kref would choke either Jenkins or the indexer. If that's not the case, we can merge https://github.com/KSP-CKAN/NetKAN/pull/3893 and that'll get us 90% of the way there.

**Comment by techman83** [comment]
Ahh, it might be Jenkins that chokes. Netkan is totally fine with it, I've been testing mirror stuff with ckans pushed through netkan first.

**Pull request merged**
