### PR TITLE
1.0.4 override for RCSBuildAid

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by dbent** [comment]
#rebuild

**Comment by dbent** [comment]
@m4v I figure this is OK?

**Comment by dbent** [comment]
Reason for closing?

**Comment by plague006** [comment]
Ah my bad, that got swept with a couple old branches I was deleting.

**Comment by m4v** [comment]
I haven't played 1.0.4 because reasons, but so far nobody reported problems with the plugin so believe it should be fine.

**Pull request closed without merging**
