### PR TITLE
Putting xScience 4.14 back

### PR DESCRIPTION
**Pull request by thewebbooth**
NETKAN ate my CKAN file.
I had no references to kerbalstuff but it still replaced it with a spacedock version.
Don't have "Publish to CKAN" ticked in spacedock, wasn't ticked at kerbalstuff.
This was a one-off right?

Switched download to https because GCHQ.

Keep up the good work.

### CODE REVIEW

**Comment by politas** [comment]
Hi there! I'm glad you are happy to have your mod listed on CKAN, but I'm curious as to why you don't want us to grab the metadata from Spacedock automatically and point people to the CDN there. It makes for a lot less work when new versions are published. All you need to do is publish the new version on Spacedock, and it will automatically appear in CKAN a short time later. As long as the installation instructions and dependencies remain the same, all should go smoothly. We are also in the process of implementing a system to detect changes in installation methods / dependencies, to ease support hassles for mod authors.

CKAN was scraping metadata for xScience from Kerbalstuff before, and we've been switching mods over to Spacedock as soon as we notice an existing mod appearing there.

The set of commits you have included here for other CKAN files, pointing them to ckan1.spacedock.info, was  certainly a once-off. We have redirected links from kerbalstuff to a mirror on spacedock for all freely distributable mods that we don't have new locations for. Going forward, our preference is to use netkan to keep mod information up to date. I'm updating the abstract and homepage information with the details you have given here.

**Comment by thewebbooth** [comment]
Well, no worries one way or the other, but my hosting didn't just disappear.  [x] Science! didn't drop off the Internet with kerbalstuff.  As I have rock-solid hosting of my own it seems daft not to use it.

I've always updated my CKAN files this way before they have never been overwritten by NETKAN before.  I only got the kerbalstuff account because some of my users asked for it.

**Comment by politas** [comment]
Ok, I'm terribly sorry, I think I got thrown off by that first commit in this PR. It does look like we were never scraping kerbalstuff for [x] Science!, and pointing at Spacedock was most likely simply due to seeing it appear in the "New mods" list there.
If you want to keep submitting ckan files for each version, we can go back to that method.

**Comment by dbent** [comment]
An alternative is to simply use a [metanetkan](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ckannetkanurl) and then keep version-specific information in [`x_netkan_override`](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#x_netkan_override) blocks, i.e. [`HotSpot.netkan`](https://raw.githubusercontent.com/Apokee/HotSpot/master/HotSpot.netkan). That scrapes from GitHub but you don't have to, just specify the `version` manually and put the `download` in an `x_netkan_override` block.

Then you have complete control over the metadata and don't have to send a PR to us for each update.

**Comment by politas** [comment]
I've put in an override block to our netkan in PR#3387 to redirect the download to your server.

**Pull request closed without merging**
