### PR TITLE
Back-fill missing InterstellarExtended releases

### PR DESCRIPTION
**Pull request by DasSkelett**
Done via
```
netkan.exe --releases 57 KSPInterstellarExtended.netkan
```

See https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1260-baikonur/&do=findComment&comment=3606315 and my answer.

### CODE REVIEW

**Comment by DasSkelett** [comment]
Oups...
```
tar: CKAN-meta-master/SETI-BalanceMod/SETI-BalanceMod-1.2.0.0.ckan: Wrote only 2560 of 4273 bytes
tar: CKAN-meta-master/SETI-BalanceMod/SETI-BalanceMod-1.2.1.0.ckan: Cannot write: No space left on device
```

Well, those are 9 GiB :)

**Comment by HebaruSan** [comment]
I believe that'll be this `tar` command:

https://github.com/KSP-CKAN/xKAN-meta_testing/blob/4284f1f5aba7cc1294a9ae5226685b53108fe9b5/CKAN-meta/build.sh#L93

That command unpacks the `metadata.tar.gz` file from the CKAN-meta repo in preparation for injecting the new/changed .ckan files into it. This fails because the cache and the dummy KSP instance have filled the testing VM's disk.

I guess our options are:

- Increase the size of the VM's disk
- Split this into 41 separate pull requests
- Bypass the validation scripts this time

**Comment by HebaruSan** [comment]
OK, I've looked at the generated metadata, and I think it's safe to merge despite the script failing.

Note for posterity: This mod is apparently releasing **five** separate parallel builds each time it makes changes, one for KSP 1.3.1, one for KSP 1.4.5, one for KSP 1.5.1, one for KSP 1.6.1, and one for KSP 1.7.0. If that continues, then either we'll need the SpaceDock web hook fixed, or we'll need to update the bot to check more releases, or we'll be back here backfilling releases manually again.

**Comment by techman83** [comment]
goodnews

Spacedock is being moved to a new host. I happend to catch VITAS and the hook has been fixed :smile:

**Comment by HebaruSan** [comment]
@techman83, looks like it worked! These releases would not have been indexed otherwise:

https://github.com/KSP-CKAN/CKAN-meta/compare/714926d...cd2f26e

**Pull request merged**
