### PR TITLE
Update with spacedock metadata but curse download until netkan is working

### PR DESCRIPTION
**Pull request by plague006**
Because @necrobones is good people. =)

### CODE REVIEW

**Comment by plague006** [comment]
Jenkins you were doing so good.. why you cray cray again?

**Comment by plague006** [comment]
Wait a sec.. I think I remember something like this.. testing now.

**Comment by plague006** [comment]
So for posterity: If Jenkins keeps testing the same unrelated file, it's because that file was merged but is invalid or broken in some way. In this case `AmpYearPowerManager/AmpYearPowerManager-1-V1.1.1.0.ckan` had a download link that was 404.

**Comment by politas** [comment]
This shouldn't affect local testing, though?

**Comment by plague006** [comment]
Correct it doesn't affect local testing, but until it's addressed in ckan-meta Jenkins will be unable to properly test any (ckan-meta) PRs.

**Comment by NecroBones** [comment]
What exactly happened? The Netkan not processing properly?

**Comment by plague006** [comment]
@NecroBones: Aye, the netkan for FuelTanksPlus is failing when the bot runs. We're not yet sure why it's failing at the moment, but I manually edited the .ckan so that users can install it (until we get the netkan working properly).

**Comment by NecroBones** [comment]
Huh, strange. Anyway, thanks! Let me know if there's anything I can do to help.

**Comment by techman83** [comment]
Likely the file has changed, but not the url path. `Cannot find central directory`.  I'll remove the cached zip file.

**Comment by plague006** [comment]
@techman83 sadly, that hasn't fixed the issue.

**Comment by techman83** [comment]
@plague006 the netkan will probably need altering, the indexer just runs netkan.exe over them all.

**Comment by techman83** [comment]
@plague006 never mind. There were _a lot_ of cached things for FuelTanksPlus :-)

**Pull request closed without merging**
