### PR TITLE
Add Homepage to reflectionPlugin

### PR DESCRIPTION
**Pull request by politas**
I think I'm reading the schema correctly, here. I don't know what previous versions of the schema contained, so I'm bumping this file to 1.4

### CODE REVIEW

**Comment by Dazpoet** [comment]
took me a while to see the problem but you don't need [ ] around the resources :)

**Comment by politas** [comment]
Is that because there's only a single sub-entry?

**Comment by Dazpoet** [comment]
No, you add all resources inside the {} like this:

```
"resources" : { "resource-1" : "link", "resource-2" : "link", ..., "resource-n" : "link" }
```

Why, you'll have to ask someone who knows JSON but that's how it works.

**Comment by politas** [comment]
Ah, I see, [] indicate an array, while {} indicates an object with a collection of properties (which may in turn be objects)

**Pull request merged**
