### PR TITLE
Rewrite versions to be more specific!

### PR DESCRIPTION
**Pull request by pjf**
As discussed in KSP-CKAN/CKAN#1156, sometimes we see older versions of
mods that have "generic" KSP versions (eg: 1.0), even though newer
versions of those same mods have specific versions (eg 1.0.1). These has
been a side-effect of how KS returns KSP version numbers to us.

This patch adds ".0" to version numbers if and only if we see a later
version of the same mod that has a specific version number in the same
sequence (eg: 1.0 and 1.0.3 causes a rewrite, but 0.24 and 1.0.3 does
not).

Source code coming soon. I haven't checked it into CKAN-meta because
it's not really a place where lots of code should be hanging out.

Also attn @dbent, who identified this issue in the first place.

### CODE REVIEW

**Comment by pjf** [comment]
Here's the code I used to do this, but I'll throw it in the main CKAN `bin` directory in a separate PR.

```perl
#!/usr/bin/perl -w
use 5.010;
use strict;
use warnings;
use autodie;
use JSON;
use File::Slurp qw(read_file write_file);
use Getopt::Std;

# Find and optionally rewrite old mod versions that have overly vague
# KSP versions.
# Note: You may need to run this MULTIPLE times, as it only finds the
# first file in each sequence to have incorrect data.

my %already_reported;
my %opts = (
    w => 0,     # Rewrite files containing bugs
);

my $json = JSON->new;

getopts('w',\%opts);

foreach my $dir (glob("*")) {
    # Skip anything but directories
    next if not -d $dir;

    my ($two_part_version, $two_part_file);

    foreach my $file (glob("$dir/*")) {
        # Skip anything but .ckan files
        next if $file !~ /\.ckan$/;

        my $ckan = eval { $json->decode(scalar read_file $file); };

        if ($@) { die "Error reading $file - $@"; }

        my $ksp_version = $ckan->{ksp_version};

        # Skip things without a KSP version
        next unless $ksp_version;

        # Check if this is a two-part version.
        if ($ksp_version =~ /^\d+\.\d+$/) {
            $two_part_version = $ksp_version;
            $two_part_file    = $file;
        }
        elsif ($two_part_version and $ksp_version =~ /^\Q$two_part_version\E\.\d+$/) {
            # A later release with a more specific version? That's a bug!

            next if $already_reported{$two_part_file}++;

            say "$two_part_file";
            say "# $two_part_file contains errorneous version $two_part_version obsoleted by $file";

            if ($opts{w}) {
                my $file_content = read_file $two_part_file;
                my $metadata = $json->decode($file_content);

                # Rather than simply adjust the JSON and rewrite (which causes a BIG diff)
                # we instead adjust the line in place (causing a small diff)

                $file_content =~ s{
                    ("ksp_version"\s*:\s*)"\Q$metadata->{ksp_version}\E"
                }{$1"$metadata->{ksp_version}.0"}msx
                    or die "Version substitution failed on:\n $file_content";

                write_file($two_part_file, $file_content);
                say "# Rewritten $two_part_file to use version $metadata->{ksp_version}.0";
            }
        }
    }
}
```

**Comment by pjf** [comment]
Of course jenkins hates this, because everything in it is trying to be 1.0.0 or earlier. :)

**Comment by Dazpoet** [comment]
Will these mean that we might end up appending versions to mods which have wildcards in their avc files? Aka those created as an effect of https://github.com/KSP-CKAN/CKAN/pull/1006

**Comment by techman83** [comment]
LGTM.

**Comment by pjf** [comment]
@Dazpoet : Potentially yes, but *only* if we see a later release¹ of the same mod that specifies a precise version. For example:

KerbalFoo v0.24 targets KSP 1.0
KerbalFoo v0.25 targets KSP 1.0.1

In this case v0.24 would be rewritten to use v1.0.0, since otherwise a user upgrading to KSP 1.0.2 would be offered an *older* version of the mod compared to if they were running on 1.0.1.

--

¹ Technically I've gone through mods in lexical order, rather than strictly according to the CKAN versioning rules; in this case there's a chance that we *may* have changed a *later* version to have a precise release, if an *older* version has a precise release number for the same KSP version, *and* the mods versions sort differently in lexical order as compared to `CKAN.Version` order. (Which is to say: maybe)

**Comment by dbent** [comment]
Head's up, there may be other examples, but [PlanetShine](https://github.com/KSP-CKAN/CKAN-meta/tree/master/PlanetShine) was missed in this. Versions `0.2.2.2` and `0.2.2.3` are still KSP version `1.0` while later versions are `1.0.2`. I suspect it's the lexical ordering issue @pjf brought up. If there aren't too many of these we could just make a list of them to correct manually.

**Comment by RichardLake** [comment]
InfernalRobotics had the same issue. Assuming it is the prefixed v issue.

**Pull request merged**
