### PR TITLE
Add AUC Aeronautic technology from Curse

### PR DESCRIPTION
**Pull request by politas**
Picked a version number at random. I don't know why my CKAN-meta keeps showing all these catch-up commits when my NetKAN repo doesn't do the same.

### CODE REVIEW

**Comment by politas** [comment]
Successfully tested locally.

**Comment by plague006** [comment]
> Picked a version number at random.

Let's instead use the version number from http://forum.kerbalspaceprogram.com/index.php?/topic/130683-wip-105-auc-aeronautic-mods-001/ (which is `0.0.1`)

**Comment by politas** [comment]
Now, I just knew there was somewhere I could get a version number! Thanks.

**Comment by plague006** [comment]
Jenkins can't test this due to #969, but it passes local. Merging with my thanks.

**Pull request merged**
