### PR TITLE
Add MainSailor Textures 2.0

### PR DESCRIPTION
**Pull request by politas**
Split into Multiple install packs, in line with details from forum thread.
Removed old GammaTextures 1.1, because mod author has made the new version available at the old dropbox link

Author is going to look into uploading to Spacedock, at which time these can be used to create netkans

### CODE REVIEW

**Comment by plague006** [comment]
`ksp_version_max`

**Comment by politas** [comment]
Or that.

**Comment by politas** [comment]
Hmm, the netKAN build tests work fine for promiscuous PPTextures.

**Comment by techman83** [comment]
NetKAN's default is still on 1.0.5, maybe until 1.1.0 is released the default should be 1.0.5. I'll amend that for CKAN-meta and we can look at a good time to set the default to 1.1.0.

**Pull request closed without merging**
