### PR TITLE
Extraplanetary Launchpads 5.2.0

### PR DESCRIPTION
**Pull request by Murdabenne**
Adding the new release and updating KSP compatibility to use the new _min and _max functionality

### CODE REVIEW

**Comment by SkyMarshal** [comment]
Looking at the releases page for the github page, you could probably just set up a .netkan file and let the bot do this for you.

**Comment by SkyMarshal** [comment]
Nevermind, I thought they had a .version file (which the bot could look at in each release to get compatibility info) but it doesn't.

**Comment by Murdabenne** [comment]
Yeah that's what I was asking the author about in the forum

**Comment by pjf** [comment]
This looks good to me, thank you!

**Pull request merged**
