### PR TITLE
Update surfacelights-1.17.ckan

### PR DESCRIPTION
**Pull request by Sinomen**
As per 
https://forum.kerbalspaceprogram.com/index.php?/topic/139724-minimum-ksp-version-111-surface-mounted-lights-v117/
the KSP min version should be 1.11.0

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for another one!
This one will be slightly more complicated because it's the current version; we will want to go "upstream" to where this data comes from to fix it, so the automated systems will handle it properly...

Try editing here:

- https://github.com/ihsoft/SurfaceLights/edit/master/SurfaceLights.version

That's where the info is coming from now, so updating it will propagate through to CKAN. You can create another pull request using essentially the same steps, but @ihsoft will review it instead of the CKAN team.

**Comment by Sinomen** [comment]
I see... so for a current version, PR should be created in the mod author's repository, for older versions directly at CKAN?

**Comment by HebaruSan** [comment]
Yeah, that's how it works for mods with version files. For mods without version files, any number of other hacks might be in place that would need updating. It depends on the specific mod, so you can keep submitting things here at first and we'll figure out what to do.

**Comment by HebaruSan** [comment]
(Xref ihsoft/SurfaceLights#35)

**Comment by Sinomen** [comment]
Ok, done.

And how would I cancel/delete my PR here?

**Comment by HebaruSan** [comment]
There's a button under the text box: 

- image

But you might as well wait till the other PR gets merged, in case we do need to make any other changes on the CKAN side.

**Comment by Sinomen** [comment]
Got it, thanks! I'll leave this PR then as it is now.

**Comment by HebaruSan** [comment]
The other PR's changes have come through:  5630f29b90f51109e28137899e78404d16ab9442
Nice work! :tada:

**Pull request closed without merging**
