### PR TITLE
Add Ksc plus plus

### PR DESCRIPTION
**Pull request by politas**
Ref #947
Only a Dropbox download, unfortunately.

### CODE REVIEW

**Comment by politas** [comment]
Can anyone suggest how I go about rebasing?

**Comment by politas** [comment]
Failing on ABLaunchers kerbalstuff download????? What has this to do with that?

**Comment by airminer** [comment]
The command you are looking for is "git rebase <upstream> [<branch>]" 

It rebases the current branch, or optionally the <branch> on top of the <upstream> branch.

**Comment by airminer** [comment]
The checks are out of whack. They fail on stuff the bot added since the last check, not on stuff from the pull request.

**Comment by airminer** [comment]
So, for example if you have this repo as the remote branch "upstream", you would:
`git remote update
git rebase upstream`
from the branch you are rebasing.

**Comment by politas** [comment]
I'll try again.

**Comment by airminer** [comment]
If you have the current repo on your master, you can just
`git rebase master`
from the patch branch.

**Comment by politas** [comment]
I think my local master is weirdly screwed. Trying to rebase my master on upstream, I get:
fatal: Needed a single revision
invalid upstream upstream

**Comment by politas** [comment]
Is there an easy way to completely refresh my fork back to the upstream?

**Comment by techman83** [comment]
The wiki has some good info :-)
https://github.com/KSP-CKAN/CKAN/wiki/Workflow

**Comment by airminer** [comment]
Okay, so have you set up this repo as "upstream"?
If no, then: `git remote add upstream https://github.com/KSP-CKAN/CKAN-meta.git`

Once you have it, the following:
```
git remote update
git checkout master
git pull upstream
git checkout KSCPlusPlus
git reset --hard 6fa3a5f
git rebase master
```
This removes the merges, and rebases instead.
Then, if everything looks OK:
`git push --force`

**Comment by Olympic1** [comment]
Looks like your rebase worked, so merging with my thanks.

Also thanks for the helping him @airminer and @techman83

**Comment by politas** [comment]
Thanks @airminer and @techman83 for the advice. I'm not sure I understand what was wrong, but I think it's fixed now.

**Pull request merged**
