### PR TITLE
Fix current RO version

### PR DESCRIPTION
**Pull request by Olympic1**
@NathanKell edited the external netkan file for the next release of RO, but these changes get applied for the current release that is compatible for KSP 1.0.4

### CODE REVIEW

**Comment by NathanKell** [comment]
So...how _should_ this be handled then?

**Comment by Olympic1** [comment]
It would be better if the netkan file on the RO repo got updated together with or after the new release for 1.0.5, because now it checks the file every ~3 hours and updates the file for KSP 1.0.4.

**Comment by NathanKell** [comment]
Ok. But then won't it do it then, too?

**Comment by Olympic1** [comment]
Technically it should update the new file

**Comment by NathanKell** [comment]
Ok. I'll revert the two commits and only make them when RO's ready to go.

**Comment by Olympic1** [comment]
Closing as the file for KSP 1.0.4 is fixed

**Pull request closed without merging**
