### PR TITLE
Clean up 1.99.99 versions

### PR DESCRIPTION
**Pull request by HebaruSan**
Historical updates for KSP-CKAN/NetKAN#7516. Various SETI mods show up as compatible on 1.8 even though even the most recent releases aren't. There are historical versions with a bad max game version of 1.99.99. Now they're fixed.

To make this easier, other occurrences of 99.99 are also replaced with better data, in some cases "any", in others specific versions.

### CODE REVIEW

**Comment by techman83** [comment]
We might want to re-visit PRs that contain a lot of changes. IMO we should probably break them up into groups. Currently the CI is essentially DoS'd
> Build has been executing for 3 hr 18

**Comment by HebaruSan** [comment]
Oops, sorry about that.  What's the Y axis on that graph, available credits?

**Comment by techman83** [comment]
Np, yeah that's available credits.

**Comment by techman83** [comment]
I cancelled the builds, they were never going to succeed in a reasonable amount of time. It was only half way through the second to last commit of contract configurator.

Suggest breaking them up by identifier rather then these mega PRs.

**Comment by HebaruSan** [comment]
Alright, I can do some git magic to migrate changes...

**Comment by HebaruSan** [comment]
Ready to push a rebased version of this with the ones from #1593 removed, but we'll give Jenkins a rest for a while first...

**Comment by techman83** [comment]
It's a t2.micro, credits accumulate at a rate of 6 per hour. 1 credit = 100% cpu for 1 minute and the t2.micro has a baseline performance of 10%.

**Comment by HebaruSan** [comment]
Good to know. What's the maximum total credits it can accumulate?

**Comment by techman83** [comment]
144 on a t2

**Pull request merged**
