### PR TITLE
Update RealPlume epochs to get sources and ordering straight.

### PR DESCRIPTION
**Pull request by politas**
RealPlume was originally drawn from the Realism Overhaul github and borrowed version numbers from there. There are two epochs since it gained its own Github. 

I think I've got a set of metadata here that will work, though there's also KSP-RO/RealPlume#16 to update the netkan details required, which might invalidate a bit of this. I'm tempted to say let's not merge this until the netkan is fixed, and then I'll sort that last version.

### CODE REVIEW

**Comment by politas** [comment]
KSP-RO/RealPlume#16  has been merged and this should be all set to go. Can someone check those errors and merge it? O am a little worried about the Update and rename RealPlume-1-v10.4.9.ckan to RealPlume-2-v10.4.9.ckan followed by the Delete RealPlume-2-v10.4.9.ckan. I'd rather just pull out the rename and delete the 1-v10 to avoid messing with the current file, but I can't figure out how to remove specific commits from my patch.

**Comment by Olympic1** [comment]
Is this good to merge, or do you need to change something?

**Comment by politas** [comment]
Should be good to merge.

**Comment by Olympic1** [comment]
Ok, merging with a huge thanks.

**Pull request merged**
