### PR TITLE
Add modules for DLC

### PR DESCRIPTION
**Pull request by HebaruSan**
This PR adds a .ckan file for each known version of each DLC, based on the change logs in their `readme.txt` files, following the format created in KSP-CKAN/CKAN#3038.

The spec version is `v1.28`, so it should be safe to merge this without disrupting the existing clients, all of which are on `v1.27` or earlier.

### CODE REVIEW

**Comment by HebaruSan** [comment]
The validation error will be eliminated after KSP-CKAN/CKAN#3038 is merged:

```
961 [1] FATAL CKAN.NetKAN.Program (null) - BreakingGround-DLC has no $kref field, this is required when no download url is specified
```

**Comment by Olympic1** [comment]
The MakingHistory-DLC-1.6.1.ckan is missing.

**Comment by HebaruSan** [comment]
> The MakingHistory-DLC-1.6.1.ckan is missing.

Was there such a version? It's not listed in the readme.txt's change log, which goes directly from v1.6.0 to v1.7.0.

**Comment by HebaruSan** [comment]
OK, the wiki confirms it...

image

https://wiki.kerbalspaceprogram.com/wiki/1.6.1

**Comment by Olympic1** [comment]
> It's not listed in the readme.txt's change log
It was a very small bugfix release

**Comment by HebaruSan** [comment]
> The validation error will be eliminated after KSP-CKAN/CKAN#3038 is merged:

Actually it's probably still going to fail during the `install` command, right?...

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Ooh:

```
Validating metadata: 'BreakingGround-DLC/BreakingGround-DLC-1.0.0.ckan'
1034 [1] FATAL CKAN.NetKAN.Program (null) - BreakingGround-DLC 1.0.0 requires CKAN v1.28, we can't read it.
Build step 'Execute shell' marked build as failure
```

Naturally when I tested this I had updated my local `CHANGELOG.md` to version 1.28.

**Comment by DasSkelett** [comment]
Okay, I don't think we'll get the CI to succeed on this PR.
The next step will be trying to install them, which will fail, too...

I checked them locally, should be fine.

**Pull request merged**
