### PR TITLE
Added KW Community fixes

### PR DESCRIPTION
**Pull request by TeddyDD**
by @linuxgurugamer
[Forum thread](http://forum.kerbalspaceprogram.com/threads/129918-KW-Rocketry-Community-Fixes)
I'm not sure what licence is this. At forum
>License is GPL  

however KS says MIT

This PR contains 3 packages
KWRocketry-2.7.1 - this is 2.7 but set to works on KSP 1.0.4 and depends on Community-Fixes
KWRocketry-CommunityFixes -  Community-Fixes :+1: 
KWRocketry-CommunityFixes-interstage - optional config. May break your crafts. 

Would be great if someone test it. Works for me.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
It is the GPLv3

I updated kerbalstuff, thanks for letting me know

JBB

**Comment by plague006** [comment]
There's also https://github.com/KSP-CKAN/NetKAN/pull/1996 related to this. As far as these .ckans, they install just fine via CKAN, however I have a few issues to bring up:

`KWRocketry-CommunityFixes-interstage` and `KWRocketry-CommunityFixes` have the same `name` meaning one will be hidden (interstage specifically) 

A `version` of `2.7.1-community` will supersede `2.7.1` so I would also suggest naming it `2.7.0-community`.

**Comment by linuxgurugamer** [comment]
OK, I'm puzzled.

Did someone create another mod called KWRocketry-CommunityFixes-interstage?

**Comment by plague006** [comment]
No. `interstage` is split because (as you described) it can break saves, so we want that as clear as possible for users installing it.

**Comment by linuxgurugamer** [comment]
That's fine, but I didn't do that.

Is this something you'd liek me to do, or are you already handling it?

**Comment by plague006** [comment]
@TeddyDD is handling it afaik.

**Comment by TeddyDD** [comment]
@plague006 Thanks for suggestions :rocket:

**Comment by plague006** [comment]
Continues to pass local testing.
Merging this to get `KWRocketry-2.7.0-community.ckan` set up and will create .netkans for the community fixes shortly.

Thanks for the work @TeddyDD

**Comment by linuxgurugamer** [comment]
Thank you all for the work and support.

In the future, if/when I need to update the community fixes, I assume 
all I will need to do is update Kerbalstuff, and CKAN will pick it up 
automatically, right?

LinuxguruGamer aka JBB

**Comment by TeddyDD** [comment]
@linuxgurugamer As long as you don't do something really weird (like rename mod folder) yes :)

**Pull request merged**
