### PR TITLE
Create GGsDiverseLasses.ckan

### PR DESCRIPTION
**Pull request by monstrim**

### CODE REVIEW

**Comment by monstrim** [comment]
"All checks have failed".

Click "detais":

"Identified problems
	
No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it."

...so, what do I do now?

**Comment by politas** [comment]
You can click on "Console Output" on the left to see more information. In this case, it's complaining about your license, which doesn't match any on the ones listed in the [schema](https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema)

You need to add "CC-" at the start - 

    "license"     : "CC-BY-NC-SA-4.0",

I don't think it's going to complain, but you also have an unneccesary array on your author line. Make it:

    "author"      : "GreeningGalaxy",

And that will work fine. The square brackets are only required when listing multiple authors.

**Comment by politas** [comment]
Looks like a nice set of female heads!

**Comment by politas** [comment]
Actually, if you could change the filename to GGsDiverseLasses-1.0.ckan as well, that would fit the standard naming scheme.

**Comment by monstrim** [comment]
Trying again, now there's this:

CKAN.FileNotFoundKraken: Trying to install GGsDiverseLasses 1.0, but it's not downloaded or download is corrupted

I just downloaded fine here, tho.

**Comment by monstrim** [comment]
Fine.

**Pull request closed without merging**
