### PR TITLE
Add Kopernicus Bleeding Edge repository

### PR DESCRIPTION
**Pull request by R-T-B**
People might want this...  or not.  Who knows?

### CODE REVIEW

**Comment by HebaruSan** [comment]
That's the beauty of opt-in, if they don't want it, they don't have to have it. :+1:

**Comment by HebaruSan** [comment]
I tried downloading the .tar.gz, and I noticed a few possible syntax/validation issues with the .ckan files. Is there a place where I can submit fixes?

**Comment by R-T-B** [comment]
> 
> 
> I tried downloading the .tar.gz, and I noticed a few possible syntax/validation issues with the .ckan files. Is there a place where I can submit fixes?

Sure, surprised it wasn't worse off as i basically best-guessed it.  I'll upload it to a github repo, just a moment.

**Comment by R-T-B** [comment]
https://github.com/R-T-B/CKAN-meta-dev-Kopernicus_BE

**Comment by HebaruSan** [comment]
Awesome, see R-T-B/CKAN-meta-dev-Kopernicus_BE#1

**Comment by HebaruSan** [comment]
Alright, let's give this a try!!

**Comment by R-T-B** [comment]
Lookin good, thanks for the help with the syntax!  I just got done learning ModuleManager syntax recently so it's easy to get things scrambled... lol

**Pull request merged**
