### PR TITLE
Re-freezes Kerbalism 2.2.0 (hopefully)

### PR DESCRIPTION
**Pull request by steamp0rt**
lol i forgot to downgrade version file

### CODE REVIEW

**Comment by HebaruSan** [comment]
The bot will keep re-indexing it as long as it's still on SpaceDock.

**Comment by steamp0rt** [comment]
Yes but the versioning is based on KSP-AVC. Hmmm.

**Comment by steamp0rt** [comment]
Oh wait... KSP-AVC is coming from SpaceDock. Hm.

**Comment by DasSkelett** [comment]
I see, my freeze has not worked. @HebaruSan, wouldn't it make sense to tell the bot to skip frozen ckans too and don't create new ones?
@steamp0rt, I think the only way to solve this right now ist to freeze the .netkan too, to keep the bot from indexing.

**Comment by HebaruSan** [comment]
Why is it still on SpaceDock?

**Comment by steamp0rt** [comment]
... because i'm dumb and just realized i have to change the default version.

**Comment by steamp0rt** [comment]
:man_facepalming:

**Comment by steamp0rt** [comment]
i feel so embarassed

**Comment by HebaruSan** [comment]
OK, I think whatever you changed has helped. Running netkan locally, I get 2.1.2 now, and the bot has already updated it, which should mean that 2.2.0 won't get regenerated. Makes sense to merge now.

**Pull request merged**
