### PR TITLE
Remove redundant and non-spec resources.github

### PR DESCRIPTION
**Pull request by HebaruSan**
Several older files have `resources.github`, usually like this:

```json
    "resources": {
        "github": {
            "url": "https://whatever/",
            "releases": true
        }
    },
```

This was removed from the spec in KSP-CKAN/CKAN#253, as suggested in KSP-CKAN/CKAN#215. Apparently it was for an old pre-`$kref` design for Netkan, which (would have?) looked for new releases on GitHub if `resources.github.releases` was true.

Now this is replaced with `resources.repository` if not already set, or removed otherwise.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Finally found 1.0.1's build id! https://github.com/KSP-CKAN/CKAN/commit/9fffdf3f960a5b7a9cab403668e88260a5d62c10

**Comment by HebaruSan** [comment]
#rebuild

**Comment by DasSkelett** [comment]
Woaaah, nice job!

**Comment by techman83** [comment]
If those are mods are F/OSS licensed, they should have URLs on archive.org we can link to.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
The module downloading code already falls back to archive.org URLs, so that should already be accounted for. I think in this case they went offline before the archiving was a thing.

**Comment by HebaruSan** [comment]
... OK, that is true for the ones that actually failed, but I did jump to the conclusion that others needed freezing because they were gone from GitHub, and some of _those_ *are* on archive.org. I'll go back and unfreeze them before merging.

**Pull request merged**
