### PR TITLE
Add RCSSounds

### PR DESCRIPTION
**Pull request by dbent**
Only available on Curse or Mediafire.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Looks fine but I'd like to see the download field changed to http://addons-origin.cursecdn.com/files/2226/117/RcsSoundsV4.3.zip

These curse downloads can be very finicky at times so a direct path seems to work more often than the typ you've specified, even though that type also works (most of the time).

**Comment by Dazpoet** [comment]
#rebuild because the bot instead built DMagicOrbitalScience and some Contract mod.

**Comment by dbent** [comment]
@Dazpoet done.

**Comment by Dazpoet** [comment]
Looks fine and thank you @dbent for all your excellent help so far! You're awesome!

**Comment by dbent** [comment]
No problem, I just selfishly want All-The-Things™ in CKAN. :smiley:

**Pull request merged**
